//! The OpenAPI document, generated from the route annotations.

use utoipa::OpenApi;

/// Returns the OpenAPI document for every annotated route.
///
/// `docs/api/openapi.json` is the committed copy, and a test fails when the two differ.
/// Regenerate it with `UPDATE_OPENAPI=1 cargo test -p aarogyam-api openapi`.
#[must_use]
pub fn openapi() -> utoipa::openapi::OpenApi {
    let mut document = ApiDoc::openapi();
    // utoipa copies the licence from Cargo.toml; private crates have none, which would leave
    // an invalid empty licence object.
    document.info.license = None;
    document
}

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Aarogyam API",
        description = "The clinic platform's API. The clinic comes from the host name."
    ),
    paths(
        healthz,
        crate::v1::meta::meta,
        crate::v1::health::health,
        crate::v1::client_errors::report,
        crate::v1::me::me,
        crate::v1::me::session,
        crate::v1::me::sessions,
        crate::v1::me::revoke_session,
        crate::v1::auth::create,
        crate::v1::auth::redeem,
        crate::v1::invitations::accept,
        crate::v1::patients::recent,
        crate::v1::patients::search,
        crate::v1::patients::lookup,
        crate::v1::patients::register,
        crate::v1::patients::open,
        crate::v1::patients::edit,
        crate::v1::imports::identifiers,
        crate::v1::imports::add_identifier,
        crate::v1::imports::remove_identifier,
        crate::v1::imports::import_patients,
        crate::v1::smart_import::upload,
        crate::v1::smart_import::preview,
        crate::v1::smart_import::commit,
        crate::v1::smart_import::discard,
        crate::v1::smart_import::incomplete,
        crate::v1::smart_import::dismiss,
        crate::v1::schedule::rooms,
        crate::v1::schedule::add_room,
        crate::v1::schedule::change_room,
        crate::v1::schedule::remove_room,
        crate::v1::schedule::practitioners,
        crate::v1::schedule::add_practitioner,
        crate::v1::schedule::change_practitioner,
        crate::v1::schedule::remove_practitioner,
        crate::v1::schedule::hours,
        crate::v1::schedule::set_hours,
        crate::v1::clinic_hours::hours,
        crate::v1::clinic_hours::set_hours,
        crate::v1::schedule::leave,
        crate::v1::schedule::add_leave,
        crate::v1::schedule::remove_leave,
        crate::v1::appointments::list,
        crate::v1::appointments::book,
        crate::v1::appointments::change,
        crate::v1::appointments::set_status,
        crate::v1::check_in::check_in,
        crate::v1::queue::list,
        crate::v1::queue::walk_in,
        crate::v1::queue::set_status,
        crate::v1::queue::start_visit,
        crate::v1::walk_ins::register,
        crate::v1::quick_picks::get,
        crate::v1::today::today,
        crate::v1::visits::start,
        crate::v1::visits::list,
        crate::v1::visits::open,
        crate::v1::visits::timeline,
        crate::v1::duplicates::list,
        crate::v1::duplicates::dismiss,
        crate::v1::duplicates::merge,
        crate::v1::notices::list,
        crate::v1::notices::publish,
        crate::v1::consents::list,
        crate::v1::consents::record,
        crate::v1::consents::withdraw,
        crate::v1::legal_hold::set,
        crate::v1::patient_sessions::list,
        crate::v1::patient_sessions::revoke,
        crate::v1::dental_terms::list,
        crate::v1::dental_terms::rename,
        crate::v1::dental_terms::retire,
        crate::v1::dental_terms::restore,
        crate::v1::support_grants::list,
        crate::v1::support_grants::create,
        crate::v1::support_grants::revoke,
        crate::v1::support_grants::actions,
        crate::v1::console_support::mine,
        crate::v1::patient_notes::get,
        crate::v1::patient_notes::save_summary,
        crate::v1::visits::close,
        crate::v1::visits::create_note,
        crate::v1::visits::edit_note,
        crate::v1::visits::sign_note,
        crate::v1::visits::add_addendum,
        crate::v1::visits::note_in_error,
        crate::v1::vitals::record,
        crate::v1::vitals::in_error,
        crate::v1::facts::conditions,
        crate::v1::facts::add_condition,
        crate::v1::facts::edit_condition,
        crate::v1::facts::allergies,
        crate::v1::facts::add_allergy,
        crate::v1::facts::edit_allergy,
        crate::v1::facts::confirm_allergy,
        crate::v1::facts::flags,
        crate::v1::chart::get,
        crate::v1::chart::record,
        crate::v1::chart::add_term,
        crate::v1::treatment::record_procedure,
        crate::v1::treatment::procedures,
        crate::v1::treatment::complete,
        crate::v1::treatment::procedure_in_error,
        crate::v1::treatment::create_plan,
        crate::v1::treatment::plans,
        crate::v1::treatment::accept_plan,
        crate::v1::treatment::set_item_status,
        crate::v1::files::upload,
        crate::v1::files::list,
        crate::v1::files::link,
        crate::v1::files::content,
        crate::v1::staff::list,
        crate::v1::staff::invite,
        crate::v1::staff::change,
        crate::v1::staff::roles,
        crate::v1::roles::catalogue,
        crate::v1::roles::role,
        crate::v1::roles::set_permissions,
        crate::v1::roles::create,
        crate::v1::roles::delete,
        crate::v1::settings::get_clinic,
        crate::v1::settings::update_clinic,
        crate::v1::setup::get_clinic_setup,
        crate::v1::setup::update_clinic_setup,
        crate::v1::setup::get_my_setup,
        crate::v1::setup::update_my_setup,
        crate::v1::setup::my_practitioner,
        crate::v1::setup::update_my_practitioner,
        crate::v1::setup::my_hours,
        crate::v1::setup::set_my_hours,
        crate::v1::letterhead::document,
        crate::v1::letterhead::shared_document,
        crate::v1::letterhead::upload_image,
        crate::v1::letterhead::remove_image,
        crate::v1::letterhead::image_content,
        crate::v1::website::get_settings,
        crate::v1::website::update_settings,
        crate::v1::website::upload_photo,
        crate::v1::website::describe_photo,
        crate::v1::website::delete_photo,
        crate::v1::console::clinics,
        crate::v1::console::create_clinic,
        crate::v1::console::check_slug,
        crate::v1::console::metrics,
        crate::v1::quality::quality,
        crate::v1::onboarding::clinic,
        crate::v1::onboarding::invite,
        crate::v1::onboarding::resend_owner_invitation,
        crate::v1::onboarding::applications,
        crate::v1::onboarding::approve,
        crate::v1::onboarding::reject,
        crate::v1::registrations::register,
        crate::v1::billing::price_items,
        crate::v1::billing::create_price_item,
        crate::v1::billing::update_price_item,
        crate::v1::billing::list_invoices,
        crate::v1::billing::create_invoice,
        crate::v1::billing::get_invoice,
        crate::v1::billing::edit_invoice,
        crate::v1::billing::issue_invoice,
        crate::v1::billing::void_invoice,
        crate::v1::payments::list,
        crate::v1::payments::record,
        crate::v1::payments::get,
        crate::v1::payments::void,
        crate::v1::reports::collections,
        crate::v1::reports::pending,
        crate::v1::reports::today_money,
        crate::v1::analytics::analytics,
        crate::v1::expenses::list,
        crate::v1::expenses::record,
        crate::v1::expenses::void,
        crate::v1::notifications::list,
        crate::v1::notifications::count,
        crate::v1::notifications::read,
        crate::v1::notifications::read_all,
        crate::v1::notifications::inbox,
        crate::v1::recalls::create,
        crate::v1::recalls::due,
        crate::v1::recalls::done,
        crate::v1::prescriptions::search_drugs,
        crate::v1::prescriptions::create,
        crate::v1::prescriptions::for_patient,
        crate::v1::prescriptions::last,
        crate::v1::prescriptions::get,
        crate::v1::prescriptions::edit,
        crate::v1::prescriptions::issue,
        crate::v1::prescriptions::cancel,
        crate::v1::prescriptions::create_share,
        crate::v1::prescriptions::shared_preview,
        crate::v1::prescriptions::shared_open,
        crate::v1::prescriptions::verify,
        crate::v1::public_booking::booking_options,
        crate::v1::public_booking::free_slots,
        crate::v1::public_booking::book_online,
        crate::v1::website::public_site,
        crate::v1::website::public_photo,
        crate::v1::patient_app::me,
        crate::v1::patient_app::home,
        crate::v1::patient_app::appointments,
        crate::v1::patient_app::prescriptions,
        crate::v1::patient_app::bills,
        crate::v1::patient_app::files,
        crate::v1::patient_app::redeem,
        crate::v1::patient_app::request_link,
        crate::v1::patient_app::revoke,
        crate::v1::patient_app::book,
        crate::v1::patient_app::cancel,
        crate::v1::patient_app::file_content,
        crate::v1::patient_links::access,
        crate::v1::patient_links::invite,
        crate::v1::patient_links::confirm,
        crate::v1::patient_links::decline,
        crate::v1::patient_links::revoke,
        crate::v1::patient_links::set_sharing,
        crate::v1::inventory::suppliers,
        crate::v1::inventory::create_supplier,
        crate::v1::inventory::update_supplier,
        crate::v1::inventory::delete_supplier,
        crate::v1::inventory::items,
        crate::v1::inventory::create_item,
        crate::v1::inventory::item,
        crate::v1::inventory::update_item,
        crate::v1::inventory::delete_item,
        crate::v1::inventory::summary,
        crate::v1::inventory::low,
        crate::v1::inventory::expiring,
        crate::v1::inventory::receive,
        crate::v1::inventory::use_stock,
        crate::v1::inventory::adjust,
        crate::v1::inventory::expire_batch,
        crate::dev::token,
        crate::v1::internal::drain_outbox,
    ),
    modifiers(&BearerAuth),
    tags(
        (name = "health", description = "Liveness for load balancers and Cloud Run"),
        (name = "meta", description = "Which versions of the phone apps the API serves; public"),
        (name = "session", description = "Who is signed in, and where"),
        (name = "patients", description = "A clinic's patients; clinic host only"),
        (name = "schedule", description = "A clinic's chairs, doctors, working hours and leave; clinic host only"),
        (name = "appointments", description = "The calendar, appointments and Today; clinic host only"),
        (name = "notifications", description = "Staff notifications about online bookings, read state and the clinic inbox; clinic host only"),
        (name = "queue", description = "The waiting-room queue; clinic host only"),
        (name = "clinical", description = "Visits, notes, vitals, the dental chart, treatment and files; clinic host only"),
        (name = "staff", description = "A clinic's staff, invitations and roles; clinic host only"),
        (name = "settings", description = "A clinic's own settings; clinic host only"),
        (name = "setup", description = "First-run setup: the owner's short wizard and a doctor's own one screen; clinic host only"),
        (name = "website", description = "The clinic's website: design, content, pictures, publishing and domain; clinic host only"),
        (name = "registration", description = "Clinics applying to join; public, throttled per IP"),
        (name = "inventory", description = "Stock items, suppliers, deliveries, use and expiry; clinic host only"),
        (name = "billing", description = "Price list, bills, payments, receipts and expenses; clinic host only"),
        (name = "reports", description = "Money reports for owners and finance, and the owner's Analytics; clinic host only"),
        (name = "prescriptions", description = "Prescriptions, the medicine list and patient links; clinic host only"),
        (name = "public", description = "Patient links, QR verification and self-booking and the published website on the clinic's host; reads need no sign-in"),
        (name = "patient", description = "The patient app: a signed-in patient's own records at the clinics that linked them; reads on the app host, bookings, cancellations and files on the clinic's host"),
        (name = "console", description = "Sakalya's console; console host only, staff only"),
        (name = "development", description = "Local development only; absent in deployed servers"),
        (name = "internal", description = "Scheduled jobs; local only until Cloud Scheduler's signed calls are checked")
    )
)]
struct ApiDoc;

/// Declares the `bearer` scheme: a Supabase Auth access token in `Authorization: Bearer …`.
struct BearerAuth;

impl utoipa::Modify for BearerAuth {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "bearer",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .build(),
            ),
        );
    }
}

/// Liveness check.
///
/// Answers `ok` while the process is serving; a database outage does not fail it.
#[utoipa::path(
    get,
    path = "/healthz",
    operation_id = "getHealth",
    tag = "health",
    responses(
        (status = 200, description = "The process is serving", body = String, content_type = "text/plain")
    )
)]
#[expect(
    dead_code,
    reason = "documents the route sakalya_http::health_routes serves; it is never called"
)]
fn healthz() {}
