"""Aarogyam database design: the single source for docs/database.md and the schema explorer.

Edit this file, then run `python3 scripts/gen_schema_docs.py`.

Column syntax: "name type[?] [-> table] [| note]"
  ?          the column is nullable
  -> table   foreign key (clinic tables also include org_id in the key)
  | note     short explanation

Every table with rls="clinic" also has, without listing them here:
  org_id uuid -> organizations, id uuid (primary key is (org_id, id)),
  created_at, created_by, updated_at, updated_by, and deleted_at when lifecycle="soft_delete".
Tables with rls="global" have id uuid as primary key plus created_at / updated_at.

Status types such as org_status document their allowed values. In SQL they are text columns
with a CHECK constraint: Postgres enums can't use an index under row-level security.

lifecycle says how rows change; it drives columns, triggers, grants and CI checks:
  mutable      updated in place, never deleted
  soft_delete  updated in place, removed by setting deleted_at
  finalizable  editable until issued or signed, then frozen; corrections supersede
  append_only  inserted once, never updated or deleted
  ephemeral    may be hard-deleted (sessions, join rows, queues)
schema is the Postgres schema: "aarogyam" unless stated ("audit" for the two logs).
"""

DOMAINS = [
    ("platform", "Platform", "Run by Sakalya: plans, billing clinics, feature rollout, support, platform analytics. Console only."),
    ("iam", "Identity", "People who sign in, their sessions and devices. One user can belong to many clinics."),
    ("tenancy", "Clinic setup", "The clinic itself: branches, domains, rooms, modules, roles, staff memberships, numbering."),
    ("people", "Patients and doctors", "Each clinic's own patient records, identifiers, families, referral sources and practitioners."),
    ("scheduling", "Scheduling", "Appointments, their history, and the walk-in token queue."),
    ("clinical", "Clinical", "Visits, notes, vitals, diagnoses, prescriptions, procedures, treatment plans, files and specialty data."),
    ("ops", "Clinic operations", "Lab work, inventory and stock, equipment maintenance, payroll and consultant fees."),
    ("billing", "Money", "Price list, bills, payments, refunds, expenses and daily cash closing."),
    ("notify", "Notifications", "Templates, rules, consent, recalls, campaigns, promo codes, the outbox and every message sent."),
    ("web", "Websites", "Generated clinic websites, their versions, booking requests and traffic."),
    ("trust", "Trust and audit", "Patient consents, who viewed what, every change, and data-rights requests."),
    ("onboarding", "Onboarding", "First-login progress and data imports from old software."),
]

T = dict  # readability alias

TABLES = [
    # ------------------------------------------------------------------ platform
    T(name="plans", domain="platform", rls="global",
      purpose="Subscription plans clinics can buy (Solo, Clinic, Pro, Enterprise).",
      cols=["code text | unique: solo, clinic, pro, enterprise", "name text",
            "monthly_price_paise bigint", "yearly_price_paise bigint",
            "is_public bool | hidden plans for custom deals", "sort_order int"]),
    T(name="features", domain="platform", rls="global",
      purpose="Every feature that a plan can include or limit.",
      cols=["key text | unique, e.g. website_builder, whatsapp_campaigns", "name text",
            "kind feature_kind | boolean or limit", "description text"]),
    T(name="plan_features", domain="platform", rls="global",
      purpose="What each plan includes, and its limits.",
      cols=["plan_id uuid -> plans", "feature_id uuid -> features", "included bool",
            "limit_value int? | e.g. 2000 messages a month"],
      notes="Primary key (plan_id, feature_id)."),
    T(name="subscriptions", domain="platform", rls="global",
      purpose="Which plan a clinic is on and whether it is paid up.",
      cols=["org_id uuid -> organizations", "plan_id uuid -> plans",
            "status subscription_status | trialing, active, past_due, paused, canceled",
            "period_start date", "period_end date", "trial_ends_at timestamptz?",
            "razorpay_subscription_id text?", "canceled_at timestamptz?"]),
    T(name="saas_invoices", domain="platform", rls="global",
      purpose="Sakalya's own GST invoices to clinics for the subscription.",
      cols=["org_id uuid -> organizations", "subscription_id uuid -> subscriptions",
            "number text | Sakalya's invoice series", "amount_paise bigint", "gst_paise bigint",
            "status saas_invoice_status | issued, paid, void", "razorpay_payment_id text?",
            "issued_at timestamptz"]),
    T(name="entitlement_overrides", domain="platform", rls="global",
      purpose="Per-clinic exceptions to the plan: promos, grandfathering, custom deals.",
      cols=["org_id uuid -> organizations", "feature_id uuid -> features", "included bool",
            "limit_value int?", "reason text", "expires_at timestamptz?",
            "granted_by uuid -> platform_users"]),
    T(name="usage_counters", domain="platform", rls="global",
      purpose="How much of each limited feature a clinic used this month.",
      cols=["org_id uuid -> organizations", "feature_id uuid -> features",
            "period date | first day of the month", "used bigint"],
      notes="Primary key (org_id, feature_id, period). Incremented by the API and worker."),
    T(name="feature_flags", domain="platform", rls="global",
      purpose="Switches that release a feature gradually, separate from plans.",
      cols=["key text | unique", "description text", "default_on bool",
            "kill_switch bool | forces off everywhere"]),
    T(name="flag_rules", domain="platform", rls="global",
      purpose="Who a flag is on for: named clinics, a percentage, a plan, a platform or app version.",
      cols=["flag_id uuid -> feature_flags",
            "kind flag_rule_kind | org_list, percentage, plan, platform, min_app_version",
            "value jsonb", "priority int"]),
    T(name="platform_users", domain="platform", rls="global", star=True, lifecycle="mutable",
      purpose="Sakalya staff who can use the console, and their role.",
      cols=["user_id uuid -> users", "role platform_role | owner, support, onboarding, analyst",
            "active bool"]),
    T(name="auth_handoffs", domain="platform", rls="global", lifecycle="ephemeral",
      purpose="Central sign-in: one-time codes that hand a session to one clinic or console host, valid 60 seconds.",
      cols=["code_hash text | unique, SHA-256 of the code; the code is never stored", "user_id uuid -> users",
            "target_host text | the only host that may redeem it", "expires_at timestamptz",
            "redeemed_at timestamptz? | first attempt uses it up", "redeemed bool? | whether that attempt gave a session"],
      notes="Written and redeemed only through app.auth_handoff_create() and app.auth_handoff_redeem()."),
    T(name="clinic_applications", domain="platform", rls="global", star=True, lifecycle="mutable",
      purpose="Clinics asking to join from the public landing page; staff approve or reject them in the console.",
      cols=["clinic_name text", "city text", "specialty specialty | dental, general",
            "contact_name text", "email text | one pending application per address",
            "phone_e164 text?", "message text?",
            "status application_status | pending, approved, rejected",
            "submissions int | times the address applied while pending",
            "decision_reason text?", "decided_by uuid? -> users", "decided_at timestamptz?",
            "created_org_id uuid? -> organizations | the clinic approval created"],
      notes="No grants: the API reaches it through definer functions only. Approval creates the clinic, the owner's invitation and the invitation email in one transaction."),
    T(name="support_grants", domain="platform", rls="global",
      purpose="Time-limited permission a clinic gives Sakalya support to look inside its data.",
      cols=["org_id uuid -> organizations", "granted_by uuid -> users",
            "platform_user_id uuid? -> platform_users | null means any support agent",
            "scope support_scope | settings_only, read_records", "starts_at timestamptz",
            "expires_at timestamptz", "revoked_at timestamptz?"]),
    T(name="announcements", domain="platform", rls="global",
      purpose="Release notes and notices shown inside the clinic apps.",
      cols=["title text", "body text", "audience jsonb | plans, roles, platforms",
            "starts_at timestamptz", "ends_at timestamptz?"]),
    T(name="org_daily_stats", domain="platform", rls="global",
      purpose="Per-clinic daily counts for the console. Counts only, never patient data.",
      cols=["org_id uuid -> organizations", "day date", "active_users int", "new_patients int",
            "appointments int", "visits int", "billed_paise bigint", "messages_sent int",
            "storage_bytes bigint"],
      notes="Primary key (org_id, day). Written nightly, copied to BigQuery."),

    # ------------------------------------------------------------------ iam
    T(name="users", domain="iam", rls="user", star=True, lifecycle="mutable",
      purpose="Anyone who signs in: staff, doctors, patients, Sakalya staff.",
      cols=["auth_uid uuid | Supabase Auth user id, unique", "phone_e164 text? | unique",
            "email text?", "display_name text", "locale text | en-IN, hi-IN, mr-IN ...",
            "status user_status | active, disabled", "last_seen_at timestamptz?"]),
    T(name="sessions", domain="iam", rls="user", star=True, lifecycle="ephemeral",
      purpose="Signed-in sessions, so a stolen phone or idle PC can be signed out.",
      cols=["user_id uuid -> users", "provider_session_id uuid | session_id claim in the JWT",
            "device_id uuid? -> devices", "audience session_audience | clinic, patient, platform",
            "last_active_at timestamptz", "expires_at timestamptz", "revoked_at timestamptz?",
            "revoke_reason text?"]),
    T(name="devices", domain="iam", rls="user", star=True, lifecycle="mutable",
      purpose="Phones and browsers a user signs in from, with push tokens.",
      cols=["user_id uuid -> users", "platform device_platform | android, ios, web",
            "model text?", "app_version text?", "push_token text?",
            "push_token_updated_at timestamptz?"]),

    # ------------------------------------------------------------------ tenancy
    T(name="organizations", domain="tenancy", rls="global", star=True, lifecycle="mutable",
      purpose="A clinic business, the tenant. Everything clinic-owned points here.",
      cols=["slug text | unique, the subdomain: smilecatchers", "name text", "legal_name text?",
            "number_prefix text | 1 to 3 capital letters: SC in SC-1042",
            "specialty text | dental in Phase 1A; general later",
            "status org_status | trial, active, suspended, churned",
            "timezone text | default Asia/Kolkata", "gstin text?"],
      notes="Members can read only their own clinic's row. The console creates clinics through app.create_clinic()."),
    T(name="branches", domain="tenancy", rls="clinic", star=True, lifecycle="soft_delete",
      purpose="Locations of a clinic. Single-location clinics have one.",
      cols=["slug text | unique per clinic", "name text", "address jsonb", "phone_e164 text?",
            "gstin text? | when the branch has its own GST registration",
            "state_code text? | GST state code, e.g. 27 for Maharashtra; the place of supply",
            "is_default bool | exactly one per clinic"]),
    T(name="org_domains", domain="tenancy", rls="global", star=True, lifecycle="mutable",
      purpose="Host names that resolve to a clinic: its portal and its website.",
      cols=["org_id uuid -> organizations",
            "hostname text | unique, lower case: smilecatchers.aarogyam.example, smilecatchers.in",
            "kind domain_kind | portal, website", "is_primary bool",
            "cloudflare_hostname_id text?", "verified_at timestamptz? | only verified hosts resolve",
            "edge_status text? | portal rows: pending, ready, failed (served at the edge yet?)",
            "edge_attempts int", "edge_next_attempt_at timestamptz? | when the outbox job tries next",
            "edge_error text? | short reason, no secrets", "edge_ready_at timestamptz?"],
      notes="Read before the clinic is known, through app.resolve_clinic_host(); cached in memory for a short time. "
            "New portal rows start pending (trigger); the outbox job makes them work (app.edge_hosts_claim)."),
    T(name="slug_history", domain="tenancy", rls="global",
      purpose="Old slugs, so renamed clinics, doctors and pages keep redirecting.",
      cols=["entity slug_entity | organization, practitioner, site_page", "entity_id uuid",
            "old_slug text", "changed_at timestamptz"]),
    T(name="rooms", domain="tenancy", rls="clinic", star=True, lifecycle="soft_delete",
      purpose="Chairs, rooms and labs that appointments can be booked into.",
      cols=["branch_id uuid -> branches", "name text | unique per branch", "kind room_kind | chair, room, lab",
            "active bool", "sort_order smallint"]),
    T(name="org_modules", domain="tenancy", rls="clinic",
      purpose="Specialty modules switched on for a clinic, with their settings.",
      cols=["module_key text | dental, general, obstetrics, pediatrics ...", "enabled_at timestamptz",
            "settings jsonb | e.g. tooth numbering FDI or Universal"]),
    T(name="org_settings", domain="tenancy", rls="clinic", star=True, lifecycle="mutable",
      purpose="One row per clinic: branding, bill and prescription settings, defaults.",
      cols=["branding jsonb | colours, logo asset", "billing jsonb | GST, bill footer",
            "prescription jsonb | letterhead layout", "notifications jsonb | quiet hours, sender",
            "booking jsonb | online booking: enabled, slot_minutes, buffer_minutes, auto_confirm, horizon_days, min_notice_minutes"],
      notes="Primary key (org_id): exactly one row per clinic."),
    T(name="assets", domain="tenancy", rls="clinic",
      purpose="Non-medical files: logos, signatures, generated PDFs, website images.",
      cols=["kind asset_kind | logo, signature, pdf, site_image", "storage_key text",
            "mime_type text", "size_bytes bigint"],
      notes="Stored in a different bucket from patient attachments."),
    T(name="permissions", domain="tenancy", rls="global", star=True, lifecycle="mutable",
      purpose="Every permission the API checks, such as patients.read.",
      cols=["key text | unique, module.action", "module text", "description text",
            "scopes text[] | which of all, own, assigned it can be narrowed to; always all"],
      notes="Seeded by migrations from the Rust permission list; a test checks that they match."),
    T(name="role_templates", domain="tenancy", rls="global", star=True, lifecycle="mutable",
      purpose="Default roles copied into each new clinic: owner, doctor, front desk, assistant, finance.",
      cols=["key text | unique", "name text", "description text"]),
    T(name="role_template_permissions", domain="tenancy", rls="global", star=True, lifecycle="ephemeral",
      purpose="The permissions each default role starts with.",
      cols=["role_template_id uuid -> role_templates", "permission text | a key from permissions",
            "scope permission_scope | all, own, assigned"],
      notes="Primary key (role_template_id, permission)."),
    T(name="roles", domain="tenancy", rls="clinic", star=True, lifecycle="soft_delete",
      purpose="Named bundles of permissions. Seeded from templates; owners can add their own.",
      cols=["key text | owner, doctor, consultant, finance, front_desk, assistant, or custom",
            "name text", "is_template bool", "description text?",
            "template_id uuid? -> role_templates | the template a custom role started from"],
      notes="Key unique among live roles. Only unused custom roles are removed; standard roles never are."),
    T(name="role_changes", domain="tenancy", rls="clinic", star=True, lifecycle="append_only",
      purpose="Who changed a role's access and what it was before and after.",
      cols=["role_id uuid -> roles", "action text | created, permissions_changed, deleted",
            "changed_by uuid -> users", "before jsonb | [{key, scope}] sorted by key",
            "after jsonb | [{key, scope}] sorted by key"]),
    T(name="role_permissions", domain="tenancy", rls="clinic", star=True, lifecycle="ephemeral",
      purpose="What a role may do: module.action plus a scope.",
      cols=["role_id uuid -> roles", "permission text | a key from permissions: patients.read, finance.view",
            "scope permission_scope | all, own, assigned"],
      notes="Primary key (org_id, role_id, permission)."),
    T(name="memberships", domain="tenancy", rls="clinic", star=True, lifecycle="mutable",
      purpose="A user's place in a clinic: role, branches, status. The link between users and clinics.",
      cols=["user_id uuid -> users", "role_id uuid -> roles",
            "status membership_status | invited, active, suspended, left",
            "pin_hash text? | quick switch on shared PCs",
            "joined_at timestamptz?"],
      notes="Unique (org_id, user_id): one membership per person per clinic. Before the clinic scope is set it is read only through app.authorize()."),
    T(name="membership_branches", domain="tenancy", rls="clinic", star=True, lifecycle="ephemeral",
      purpose="Which branches a staff member works at. No rows means every branch.",
      cols=["membership_id uuid -> memberships", "branch_id uuid -> branches"],
      notes="Primary key (org_id, membership_id, branch_id). Branch-scoped permissions read this table."),
    T(name="invitations", domain="tenancy", rls="clinic", star=True, lifecycle="mutable",
      purpose="Pending invites to join a clinic.",
      cols=["phone_e164 text?", "email text?", "role_id uuid -> roles", "invited_by uuid -> users",
            "token_hash text", "expires_at timestamptz", "accepted_at timestamptz?"]),
    T(name="number_sequences", domain="tenancy", rls="clinic", star=True, lifecycle="mutable",
      purpose="Counters behind readable numbers: SC-1042, V-2026-0318, SC/26-27/000318.",
      cols=["kind sequence_kind | patient, visit, invoice, prescription, receipt, lab_order, queue_token",
            "series text | main, a separate series such as one per GSTIN, or a branch for queue tokens",
            "period text | financial year such as 26-27 or a local date for queue tokens, in the clinic's time zone; or empty",
            "next_value bigint"],
      notes="Primary key (org_id, kind, series, period). app.next_number() issues a number with INSERT ... ON CONFLICT DO UPDATE ... RETURNING in the caller's transaction, so the first number of a new year needs no setup. GST invoice numbers stay within 16 characters."),

    # ------------------------------------------------------------------ people
    T(name="patients", domain="people", rls="clinic", star=True, lifecycle="soft_delete",
      purpose="A clinic's own record of a patient. Two clinics never share this row.",
      cols=["number text | SC-1042, unique per clinic, used in URLs", "full_name text",
            "search_name text | lower-case name kept by a trigger, for prefix search",
            "sex sex | female, male, other, unknown", "date_of_birth date?",
            "birth_date_estimated bool | date_of_birth was estimated from an age",
            "phone_e164 text? | contact, never identity; indexed", "alt_phone_e164 text?", "email text?", "address jsonb?",
            "preferred_language text", "blood_group blood_group?",
            "referral_source_id uuid? -> referral_sources",
            "referred_by_patient_id uuid? -> patients", "tags text[]",
            "status patient_status | active, inactive, deceased, merged",
            "merged_into_id uuid? -> patients | set by a merge, cleared by an unmerge", "last_visit_at timestamptz?",
            "row_version bigint | starts at 1 and goes up when the record changes; sent as the ETag, checked against If-Match on edits"],
      notes="A phone number is contact information, never identity: families share numbers and numbers change. A merge only sets merged_into_id; records stay on the original patient and reads resolve to the canonical one, so a wrong merge can be undone. Number, phone and name-prefix search use plain indexes; fuzzy name search goes through app.search_patients(), because trigram matching can't use an index under row-level security. Same-phone registrations get a duplicate warning, never an automatic merge."),
    T(name="patient_identifiers", domain="people", rls="clinic", star=True, lifecycle="soft_delete",
      purpose="Extra IDs for a patient: the clinic's file number, smart card, ABHA, legacy import.",
      cols=["patient_id uuid -> patients",
            "kind identifier_kind | file_number, legacy, smart_card, abha_number, abha_address",
            "value text"],
      notes="Unique (org_id, kind, value)."),
    T(name="family_links", domain="people", rls="clinic",
      purpose="Relationships between patients in the same clinic: parent, child, spouse, guardian.",
      cols=["patient_id uuid -> patients", "related_patient_id uuid -> patients",
            "relation relation_kind | parent, child, spouse, guardian, other",
            "can_manage bool | guardian may act for this patient"]),
    T(name="referral_sources", domain="people", rls="clinic", star=True, lifecycle="mutable",
      purpose="Where patients come from, for the finance and marketing filters.",
      cols=["name text", "kind referral_kind | patient, doctor, online, walk_in, camp, insurance, other",
            "active bool"]),
    T(name="medical_history_items", domain="people", rls="clinic",
      purpose="Patient-level history: past conditions, surgeries, long-term medicines, habits, family history.",
      cols=["patient_id uuid -> patients",
            "kind history_kind | condition, surgery, long_term_medication, habit, family_history",
            "description text", "code_system code_system? | icd10, icd11, snomed, loinc, custom", "code text?", "code_display text?", "code_version text?", "since date?", "active bool", "source record_source | clinician, assistant, patient, import, device, ai_draft, abdm", "verified_by uuid? -> memberships", "verified_at timestamptz?"]),
    T(name="patient_links", domain="people", rls="user",
      purpose="Phase 3: connects a patient's own Aarogyam account to their record at each clinic.",
      cols=["user_id uuid -> users", "org_id uuid -> organizations", "patient_id uuid -> patients",
            "verified_via link_method | otp, abha, clinic_confirmed", "verified_at timestamptz",
            "revoked_at timestamptz?"],
      notes="This is the single-umbrella view: one person, many clinic records, joined only by verified links."),
    T(name="practitioners", domain="people", rls="clinic", star=True, lifecycle="soft_delete",
      purpose="Doctors who see patients at the clinic, with registration and fees.",
      cols=["membership_id uuid? -> memberships | null for a visiting consultant without a sign-in",
            "display_name text", "registration_number text?", "qualifications text?", "specialty text?",
            "calendar_color text | #RRGGBB", "active bool"],
      notes="Built in M3 with the columns the calendar needs. Planned: slug (public page), qualifications, council, signature_asset_id -> assets, default_fee_paise, is_visiting."),
    T(name="working_hours", domain="people", rls="clinic", star=True, lifecycle="ephemeral",
      purpose="Weekly hours per clinic or doctor. Split shifts are two rows.",
      cols=["practitioner_id uuid -> practitioners",
            "branch_id uuid -> branches", "weekday smallint | 1 Monday to 7 Sunday",
            "starts time", "ends time"],
      notes="Replaced as a whole per doctor. Clinic hours and valid_from/valid_to are planned."),
    T(name="leave_blocks", domain="people", rls="clinic", star=True, lifecycle="ephemeral",
      purpose="Time a doctor is unavailable. Booking into it is allowed with a warning.",
      cols=["practitioner_id uuid -> practitioners",
            "starts_at timestamptz", "ends_at timestamptz", "reason text?"]),

    # ------------------------------------------------------------------ scheduling
    T(name="appointments", domain="scheduling", rls="clinic", star=True, lifecycle="soft_delete",
      purpose="A booked slot with a doctor, optionally in a room or chair.",
      cols=["patient_id uuid -> patients", "practitioner_id uuid -> practitioners",
            "branch_id uuid -> branches", "room_id uuid? -> rooms", "starts_at timestamptz",
            "ends_at timestamptz",
            "status appointment_status | requested, booked, confirmed, arrived, in_chair, completed, cancelled, no_show",
            "kind appointment_kind | new, follow_up, procedure, emergency", "reason text?",
            "notes text? | front-desk note", "source booking_source | front_desk, phone, website, app, whatsapp",
            "cancel_reason text? | required when cancelled", "arrived_at timestamptz?",
            "seated_at timestamptz?", "completed_at timestamptz?",
            "booked_by_account uuid? | Supabase auth id of the patient who booked online; null for staff bookings",
            "row_version bigint | starts at 1 and goes up when the record changes; sent as the ETag, checked against If-Match on edits"],
      notes="Online self-bookings start as requested (or confirmed when the clinic auto-confirms); a unique index on (doctor, start) for active self-bookings backs the per-doctor check. An exclusion constraint on (org_id, room_id, time range) for active rows (not cancelled, not no-show, not deleted) stops two bookings in one chair; a doctor in two chairs at once is a warning, not an error. Status changes follow the transition table in aarogyam_domain::schedule. Visits point at appointments, not the other way round."),
    T(name="appointment_events", domain="scheduling", rls="clinic", star=True, lifecycle="append_only",
      purpose="Every status change of an appointment, for history and no-show reports.",
      cols=["appointment_id uuid -> appointments", "kind appointment_event_kind | booked, changed, status",
            "from_status appointment_status?", "to_status appointment_status?",
            "changes jsonb? | {column: [old, new]} for times, room and doctor", "at timestamptz", "note text?"]),
    T(name="queue_tokens", domain="scheduling", rls="clinic", star=True, lifecycle="mutable",
      purpose="Walk-in tokens shown on the waiting-room screen.",
      cols=["branch_id uuid -> branches", "day date | clinic's local date", "token_number int",
            "patient_id uuid -> patients", "appointment_id uuid? -> appointments | null for a walk-in",
            "practitioner_id uuid? -> practitioners",
            "status token_status | waiting, in_chair, done, left", "issued_at timestamptz",
            "called_at timestamptz?", "done_at timestamptz?"],
      notes="Unique (org_id, branch_id, day, token_number) and one token per appointment. Numbers come from number_sequences (kind queue_token, series = branch, period = local date)."),

    T(name="teleconsult_sessions", domain="scheduling", rls="clinic",
      purpose="A video or audio consultation attached to an appointment.",
      cols=["appointment_id uuid -> appointments", "provider text | video service used",
            "room_ref text | the provider's room id, never a public link",
            "status tele_status | scheduled, live, ended, failed", "started_at timestamptz?",
            "ended_at timestamptz?", "patient_joined_at timestamptz?"],
      notes="Follows the 2020 Telemedicine Practice Guidelines; the prescription is issued in the usual way afterwards."),
    # ------------------------------------------------------------------ clinical
    T(name="care_episodes", domain="clinical", rls="clinic",
      purpose="A course of care spanning visits: a root canal on tooth 36, a pregnancy, a diabetes plan.",
      cols=["patient_id uuid -> patients", "practitioner_id uuid? -> practitioners",
            "pack text?", "kind text | root_canal, pregnancy, chronic_care ...", "title text",
            "status episode_status | active, completed, cancelled",
            "started_at timestamptz", "ended_at timestamptz?"],
      notes="Optional: visits, treatment plans and specialty records may link to an episode. Built when a pack needs it."),
    T(name="encounters", domain="clinical", rls="clinic", star=True, lifecycle="mutable",
      purpose="One visit. Visit-level clinical data (complaint, vitals, notes, procedures, files) hangs off it.",
      cols=["number text | V-318, issued by the server", "patient_id uuid -> patients",
            "clinician_id uuid -> memberships | the member responsible; a doctor's practitioner record hangs off the same membership",
            "branch_id uuid -> branches",
            "appointment_id uuid? -> appointments | foreign key added once appointments exist; one visit per appointment",
            "status encounter_status | open, closed", "chief_complaint text?",
            "started_at timestamptz", "ended_at timestamptz? | set when closed"],
      notes="Unique (org_id, id, patient_id): every child row carries patient_id and a composite foreign key (org_id, encounter_id, patient_id), so a visit's notes, vitals, procedures and files can't belong to another patient. Patient-level facts (allergies, active conditions, history) live on the patient and may be updated during a visit; they do not require one. Opening a visit writes access_log."),
    T(name="clinical_notes", domain="clinical", rls="clinic", star=True, lifecycle="finalizable",
      purpose="Doctor and intake notes. Signed notes never change.",
      cols=["encounter_id uuid -> encounters", "patient_id uuid -> patients",
            "author_id uuid -> memberships",
            "kind note_kind | soap, progress, procedure, intake, front_desk",
            "body jsonb | sections: subjective, objective, assessment, plan",
            "source note_source | typed, voice, ai_draft",
            "status note_status | draft, signed, conflict, entered_in_error",
            "signed_at timestamptz?", "signed_by uuid? -> memberships | the author; only they may sign",
            "conflicts_with_id uuid? -> clinical_notes | the version this one collided with during sync",
            "error_reason text? | required when marked entered_in_error", "error_at timestamptz?",
            "error_by uuid? -> memberships",
            "row_version bigint | starts at 1 and goes up when the record changes; sent as the ETag, checked against If-Match on edits"],
      notes="Drafts are edited by their author only. Signing freezes the note: app.freeze_when() lets a signed or conflict note only move to entered_in_error (with a reason) and nothing else on it change. Never merged automatically: if a change synced from a device collides with a note already signed on the server, it is kept as a separate note with status conflict, linked by conflicts_with_id, and its author resolves it by marking one version entered_in_error. Corrections go in note_addenda."),
    T(name="note_addenda", domain="clinical", rls="clinic", star=True, lifecycle="append_only",
      purpose="Corrections and additions to a signed note, with their own author and time.",
      cols=["note_id uuid -> clinical_notes", "author_id uuid -> memberships", "body text"]),
    T(name="observations", domain="clinical", rls="clinic", star=True, lifecycle="finalizable",
      purpose="Measurements: BP, pulse, temperature, SpO2, weight, height, sugar.",
      cols=["patient_id uuid -> patients", "encounter_id uuid? -> encounters",
            "kind observation_kind | bp_systolic, bp_diastolic, pulse, temperature, spo2, weight, height, blood_sugar",
            "value_num numeric | checked against a plausible range per kind and unit",
            "unit text | UCUM: mmHg, /min, Cel, [degF], %, kg, cm, mg/dL",
            "code_system code_system? | icd10, icd11, snomed, loinc, custom", "code text? | LOINC code per kind, set by the server", "recorded_at timestamptz",
            "status observation_status | final, corrected, entered_in_error",
            "supersedes_id uuid? -> observations | the value this one corrects (same patient and kind)",
            "error_reason text?", "source record_source | clinician, assistant, patient, import, device, ai_draft, abdm", "verified_by uuid? -> memberships", "verified_at timestamptz?"],
      notes="Values are never edited: a correction is a new row that supersedes the old one, which moves to corrected and stays visible. app.freeze_when() allows only final -> corrected or entered_in_error. A row with source ai_draft needs verified_by."),
    T(name="conditions", domain="clinical", rls="clinic", star=True, lifecycle="mutable",
      purpose="Diagnoses and the problem list. Patient-level; a visit link records where it was found.",
      cols=["patient_id uuid -> patients", "encounter_id uuid? -> encounters",
            "display_text text | what the doctor wrote, always present", "code_system code_system? | icd10, icd11, snomed, loinc, custom", "code text?",
            "status condition_status | active, resolved, entered_in_error",
            "flagged bool | shown in the clinical flags banner while active", "onset date?", "note text?",
            "source record_source | clinician, assistant, patient, import, device, ai_draft, abdm", "verified_by uuid? -> memberships", "verified_at timestamptz?"]),
    T(name="allergies", domain="clinical", rls="clinic", star=True, lifecycle="mutable",
      purpose="Allergies, shown as a warning banner on the patient and on prescriptions.",
      cols=["patient_id uuid -> patients", "substance text", "code_system code_system? | icd10, icd11, snomed, loinc, custom", "code text?", "reaction text?",
            "severity severity | mild, moderate, severe", "status allergy_status | active, resolved, entered_in_error", "source record_source | clinician, assistant, patient, import, device, ai_draft, abdm", "verified_by uuid? -> memberships", "verified_at timestamptz?"]),
    T(name="drug_catalog", domain="clinical", rls="global",
      purpose="Shared list of medicines (generic name, strength, form, usual dose) for quick prescribing.",
      cols=["generic_name text", "brand_name text?", "strength text",
            "form drug_form | tablet, capsule, syrup, gel, mouthwash ...",
            "default_dose text", "default_frequency text | 1-0-1", "default_timing dose_timing?",
            "default_duration_days smallint?",
            "allergy_classes text[] | penicillin, nsaid ...; lets the allergy check match a class",
            "active bool"]),
    T(name="prescriptions", domain="clinical", rls="clinic", star=True, lifecycle="finalizable",
      purpose="A prescription from a visit: shown to staff and the patient, printed with the clinic letterhead.",
      cols=["number text? | RX-412, assigned by the server when issued",
            "encounter_id uuid? -> encounters | same patient",
            "patient_id uuid -> patients",
            "diagnosis_text text?", "advice text? | diet, care, warnings", "follow_up_on date?",
            "language text | patient's language for instructions",
            "status rx_status | draft, issued, cancelled", "issued_at timestamptz?",
            "issued_by uuid? -> memberships",
            "override_reason text? | why it was issued despite allergy alerts",
            "verify_token text? | the QR's random token; opens only validity, date and clinic, so reprints keep it",
            "letterhead jsonb? | snapshot at issue", "doctor jsonb? | name, registration number at issue",
            "recipient jsonb? | patient name, number, age and sex at issue", "footer text?",
            "cancel_reason text?", "cancelled_at timestamptz?", "cancelled_by uuid? -> memberships",
            "supersedes_id uuid? -> prescriptions | the prescription this one replaces",
            "template_id uuid? -> document_templates | print layout"],
      notes="Issued prescriptions never change (a trigger refuses): a correction cancels and reissues. The print shows the doctor's name, qualifications and registration number, generic names in capitals, the clinic's branding, and a small 'Prescribed with Aarogyam' footer with a QR code that opens the verified copy."),
    T(name="prescription_items", domain="clinical", rls="clinic", star=True, lifecycle="finalizable",
      purpose="One medicine on a prescription.",
      cols=["prescription_id uuid -> prescriptions", "line_no smallint", "drug_id uuid? -> drug_catalog",
            "drug_name text | as printed; generic name in capitals", "strength text?", "form text?",
            "dose text", "frequency text | 1-0-1",
            "timing dose_timing? | before_food, after_food, empty_stomach, bedtime, sos, as_directed",
            "duration_days smallint?", "instructions text? | in the prescription's language"]),
    T(name="procedures", domain="clinical", rls="clinic", star=True, lifecycle="finalizable",
      purpose="Treatment actually done (or planned for today) in a visit.",
      cols=["encounter_id uuid -> encounters", "patient_id uuid -> patients",
            "clinician_id uuid -> memberships", "name text", "code_system code_system? | icd10, icd11, snomed, loinc, custom", "code text?", "tooth smallint? | FDI: 11-48 permanent, 51-85 primary", "surfaces text[] | subset of M, O, D, B, L",
            "status procedure_status | planned, done, entered_in_error", "performed_at timestamptz?",
            "price_paise bigint? | the fee; billing (M5) links it to the price list",
            "treatment_plan_item_id uuid? -> treatment_plan_items | same patient; completing the procedure marks the item done",
            "note text?", "error_reason text?"],
      notes="Done procedures are frozen by app.freeze_when() (only done -> entered_in_error). One live procedure per plan item. Marking done will deduct stock via procedure_materials and can create a lab_order."),
    T(name="treatment_plans", domain="clinical", rls="clinic", star=True, lifecycle="mutable",
      purpose="A proposed course of treatment with a cost estimate, accepted or declined by the patient.",
      cols=["patient_id uuid -> patients", "clinician_id uuid -> memberships",
            "encounter_id uuid? -> encounters | the visit it was proposed in", "title text",
            "status plan_status | proposed, accepted, in_progress, completed, declined",
            "accepted_at timestamptz?"],
      notes="The estimate is the sum of its items that aren't cancelled, computed when read."),
    T(name="treatment_plan_items", domain="clinical", rls="clinic", star=True, lifecycle="mutable",
      purpose="Steps of a treatment plan, in phases.",
      cols=["plan_id uuid -> treatment_plans", "patient_id uuid -> patients | same as the plan's", "name text",
            "code_system code_system? | icd10, icd11, snomed, loinc, custom", "code text?", "tooth smallint? | FDI: 11-48 permanent, 51-85 primary", "surfaces text[] | subset of M, O, D, B, L", "phase smallint", "estimate_paise bigint",
            "status plan_item_status | proposed, accepted, done, cancelled"],
      notes="Accepting a plan accepts the chosen items and cancels the rest. An item becomes done when its procedure is done; the plan is then in_progress, and completed when no item is left to do."),
    T(name="attachments", domain="clinical", rls="clinic", star=True, lifecycle="soft_delete",
      purpose="Patient files: photos, X-rays, reports, documents, audio, signed consent.",
      cols=["patient_id uuid -> patients", "encounter_id uuid? -> encounters",
            "kind attachment_kind | photo, xray, report, document, audio, consent",
            "storage_key text | <org_id>/<id>, never from a file name", "mime_type text | from the content: JPEG, PNG, PDF, DICOM, or WebM, MP4, Ogg audio",
            "size_bytes bigint | at most 10 MB", "sha256 text", "caption text?", "tooth smallint? | FDI: 11-48 permanent, 51-85 primary", "taken_at timestamptz?",
            "source record_source | clinician, assistant, patient, import, device, ai_draft, abdm",
            "note_id uuid? -> clinical_notes | a voice recording's note, in the same visit", "addendum_id uuid? -> note_addenda | how a recording joins a signed note",
            "duration_seconds int? | a recording, 1 to 600", "language text? | a recording: en-IN, hi-IN, mr-IN"],
      notes="A trigger refuses a recording on a signed note unless it carries an addendum. Served only through short-lived signed links (HMAC, 5 minutes) issued after a permission check; each download writes access_log. Local disk in development, object storage later, behind one Storage trait."),
    T(name="voice_notes", domain="clinical", rls="clinic",
      purpose="A recorded note, its transcription status and the draft it produced.",
      cols=["attachment_id uuid -> attachments", "encounter_id uuid -> encounters",
            "duration_ms int", "language text",
            "transcript_status transcript_status | pending, processing, done, failed",
            "transcript text?", "draft_note_id uuid? -> clinical_notes"]),
    T(name="specialty_records", domain="clinical", rls="clinic", star=True, lifecycle="finalizable",
      purpose="Specialty Pack data as versioned JSON. Longitudinal: a tooth chart or pregnancy spans many visits.",
      cols=["patient_id uuid -> patients", "encounter_id uuid? -> encounters | the visit that changed it, if any",
            "module text | dental, general, obstetrics, pediatrics ...",
            "kind text | tooth (dental chart entry), pregnancy, growth", "schema_version int",
            "data jsonb | validated against the module's schema on write; dental: tooth, surface, finding, note",
            "tooth smallint? | generated from data.tooth (FDI 11-48, 51-85)",
            "surface text? | generated from data.surface: M, O, D, B, L, or none for the whole tooth",
            "status record_status | current, superseded, entered_in_error",
            "supersedes_id uuid? -> specialty_records | the entry this one replaced",
            "error_reason text?", "effective_at timestamptz", "source record_source | clinician, assistant, patient, import, device, ai_draft, abdm", "verified_by uuid? -> memberships", "verified_at timestamptz?"],
      notes="Each change writes a new row and marks the previous current one superseded, so the full history (tooth 36: caries, filled, crown) is kept. A partial unique index keeps one current entry per tooth and surface; a crown, implant or missing tooth also supersedes that tooth's surface entries. app.freeze_when() allows only current -> superseded or entered_in_error."),
    T(name="document_templates", domain="clinical", rls="clinic", star=True, lifecycle="soft_delete",
      purpose="Print and form layouts: prescriptions, bills, consent forms, certificates, letters.",
      cols=["kind doc_template_kind | prescription, invoice, consent, certificate, letter", "name text",
            "paper paper_size | a4, a5, thermal_80mm", "uses_letterhead bool | print on pre-printed paper",
            "body text | with placeholders", "pack text?", "is_default bool"],
      notes="Aarogyam's default layouts are copied into each clinic as data, so org_id is never null."),
    T(name="prescription_alerts", domain="clinical", rls="clinic", lifecycle="append_only",
      purpose="Safety warnings raised when a prescription was issued, and what the doctor did about them.",
      cols=["prescription_id uuid -> prescriptions", "prescription_item_id uuid? -> prescription_items",
            "kind alert_kind | allergy, interaction, contraindication, pregnancy, lactation, pediatric_dose, duplicate, precaution",
            "severity alert_severity | info, caution, serious", "message text",
            "source alert_source | allergy_record, drug_database, ai",
            "action alert_action | accepted_change, overridden, dismissed", "override_reason text?",
            "acted_by uuid -> memberships"],
      notes="Overrides are kept with their reason for medico-legal review."),
    T(name="drug_interactions", domain="clinical", rls="global",
      purpose="Licensed reference data: which medicines interact, how badly, and why.",
      cols=["drug_a_id uuid -> drug_catalog", "drug_b_id uuid -> drug_catalog",
            "severity alert_severity", "description text", "source_version text"],
      notes="Loaded from a licensed Indian drug database; contraindications and pregnancy categories sit alongside it."),
    T(name="document_extractions", domain="clinical", rls="clinic",
      purpose="Smart Scan: values read from a photographed paper report, waiting for confirmation.",
      cols=["attachment_id uuid -> attachments", "patient_id uuid -> patients",
            "status extraction_status | pending, extracted, confirmed, rejected", "extracted jsonb | test names, values, units, dates",
            "confirmed_by uuid? -> memberships", "confirmed_at timestamptz?"],
      notes="Nothing enters observations until a person confirms it; confirmed rows carry source = import."),
    T(name="consent_forms", domain="clinical", rls="clinic",
      purpose="A signed procedure consent.",
      cols=["patient_id uuid -> patients", "template_id uuid -> document_templates",
            "procedure_id uuid? -> procedures", "signed_at timestamptz",
            "signature_attachment_id uuid -> attachments", "pdf_attachment_id uuid? -> attachments"]),

    # ------------------------------------------------------------------ ops
    T(name="lab_vendors", domain="ops", rls="clinic",
      purpose="Outside labs: dental labs for crowns, pathology, radiology.",
      cols=["name text", "phone_e164 text?", "kind lab_kind | dental_lab, pathology, radiology"]),
    T(name="lab_orders", domain="ops", rls="clinic",
      purpose="Work sent to a lab, its due date and status.",
      cols=["number text", "vendor_id uuid -> lab_vendors", "patient_id uuid -> patients",
            "practitioner_id uuid -> practitioners", "procedure_id uuid? -> procedures",
            "work_type text | crown, bridge, denture, blood test", "details jsonb | shade, tooth",
            "sent_at timestamptz?", "due_at timestamptz?", "received_at timestamptz?",
            "status lab_status | draft, sent, received, fitted, cancelled", "cost_paise bigint"]),
    T(name="lab_payments", domain="ops", rls="clinic",
      purpose="Money paid to labs.",
      cols=["vendor_id uuid -> lab_vendors", "lab_order_id uuid? -> lab_orders", "amount_paise bigint",
            "paid_at timestamptz", "method payment_method", "reference text?"]),
    T(name="suppliers", domain="ops", rls="clinic",
      purpose="Where materials are bought.",
      cols=["name text", "phone_e164 text?", "gstin text?", "active bool", "deleted_at timestamptz?"],
      notes="Built (migration 0061). Soft delete; names are unique per clinic."),
    T(name="inventory_items", domain="ops", rls="clinic",
      purpose="Materials and medicines the clinic stocks.",
      cols=["name text", "category text?", "unit text | piece, ml, g, box, pack",
            "reorder_level bigint", "active bool", "deleted_at timestamptz?"],
      notes="Built (migration 0061). Quantities are whole units. Status is derived: critical (out, or a fifth of the reorder level or less), low (at or below it), expiring (a batch within 30 days), else ok."),
    T(name="stock_batches", domain="ops", rls="clinic",
      purpose="Received stock by batch, with expiry and cost.",
      cols=["item_id uuid -> inventory_items", "supplier_id uuid? -> suppliers", "batch_no text?",
            "expiry date?", "received_quantity bigint", "quantity bigint | remaining, never below 0",
            "unit_cost_paise bigint", "received_on date"],
      notes="Only quantity changes after the delivery (trigger). Use takes the earliest expiry first (FEFO) and never from an expired batch."),
    T(name="stock_movements", domain="ops", rls="clinic",
      purpose="Every change in stock: receive, use, adjustment, expiry. Stock history comes from here.",
      cols=["item_id uuid -> inventory_items", "batch_id uuid -> stock_batches",
            "kind text | receive, use, adjust, expire",
            "quantity bigint | signed", "reason text? | required for adjust and expire"],
      notes="Append-only; one row per batch touched; created_by is who. Procedure-linked deduction (procedure_id) comes with procedure_materials."),
    T(name="procedure_materials", domain="ops", rls="clinic",
      purpose="Materials a treatment uses, so stock deducts itself.",
      cols=["price_item_id uuid -> price_items", "item_id uuid -> inventory_items", "quantity numeric"]),
    T(name="equipment", domain="ops", rls="clinic",
      purpose="Chairs, autoclaves, X-ray units and their service schedule.",
      cols=["branch_id uuid -> branches", "name text", "serial_no text?", "purchased_at date?",
            "warranty_until date?", "service_interval_days int?"]),
    T(name="maintenance_logs", domain="ops", rls="clinic",
      purpose="Services and repairs done on equipment, and when the next is due.",
      cols=["equipment_id uuid -> equipment", "kind maintenance_kind | service, repair, amc",
            "done_at date", "cost_paise bigint", "vendor text?", "next_due_at date?", "notes text?"]),
    T(name="salary_structures", domain="ops", rls="clinic",
      purpose="A staff member's monthly salary from a date.",
      cols=["membership_id uuid -> memberships", "monthly_paise bigint", "effective_from date"]),
    T(name="payroll_entries", domain="ops", rls="clinic",
      purpose="Salary paid for a month, with deductions and advances recovered.",
      cols=["membership_id uuid -> memberships", "month date", "gross_paise bigint",
            "deductions_paise bigint", "advance_recovered_paise bigint", "net_paise bigint",
            "paid_at timestamptz?", "method payment_method?"]),
    T(name="staff_advances", domain="ops", rls="clinic",
      purpose="Salary advances given to staff and how much is recovered.",
      cols=["membership_id uuid -> memberships", "amount_paise bigint", "given_at date",
            "recovered_paise bigint"]),
    T(name="consultant_fee_rules", domain="ops", rls="clinic",
      purpose="How a visiting consultant is paid: a percentage or fixed amount per treatment.",
      cols=["practitioner_id uuid -> practitioners", "price_item_id uuid? -> price_items | null means all",
            "kind fee_kind | percent_bps, fixed", "value bigint"]),
    T(name="consultant_payouts", domain="ops", rls="clinic",
      purpose="Payments made to consultants for a period.",
      cols=["practitioner_id uuid -> practitioners", "period_start date", "period_end date",
            "amount_paise bigint", "paid_at timestamptz?", "method payment_method?"]),

    # ------------------------------------------------------------------ billing
    T(name="price_items", domain="billing", rls="clinic", star=True, lifecycle="soft_delete",
      purpose="The clinic's price list. Seeded from the specialty, then edited.",
      cols=["code text? | unique per clinic", "name text | Root canal, Scaling, Consultation",
            "category text? | consultation, preventive, endodontics, medicines …; drives the revenue mix",
            "sac_hsn text? | SAC 9993 for health care, HSN for goods", "price_paise bigint",
            "taxable bool | false for health care by a clinical establishment (exempt)",
            "tax_rate_bps int | 0, 500, 1200 or 1800; 0 unless taxable", "active bool"]),
    T(name="invoices", domain="billing", rls="clinic", star=True, lifecycle="finalizable",
      purpose="A bill to a patient. Totals are stored at issue; whether it is paid is derived from allocations.",
      cols=["number text? | SC/26-27/000318, assigned by the server when issued (at most 16 characters)",
            "series text | number series, main by default", "financial_year text? | 26-27, in clinic time",
            "patient_id uuid -> patients",
            "encounter_id uuid? -> encounters | same patient",
            "branch_id uuid -> branches",
            "doc_type invoice_doc? | tax_invoice, bill_of_supply; decided at issue",
            "status invoice_status | draft, issued, void",
            "place_of_supply text? | state code; IGST when it differs from the branch's state",
            "notes text?", "issued_at timestamptz?", "issued_by uuid? -> memberships",
            "supplier jsonb? | snapshot at issue: legal name, GSTIN, address, state",
            "recipient jsonb? | snapshot at issue: patient name and number",
            "subtotal_paise bigint", "discount_paise bigint", "taxable_paise bigint",
            "cgst_paise bigint", "sgst_paise bigint", "igst_paise bigint", "tax_paise bigint",
            "round_off_paise bigint | to the nearest rupee, -50 to 50", "total_paise bigint",
            "replaces_invoice_id uuid? -> invoices | when a voided bill is reissued",
            "void_reason text?", "voided_at timestamptz?", "voided_by uuid? -> memberships"],
      notes="Issued bills never change (a trigger refuses): corrections void and replace. Numbers are never generated offline. Payment state (unpaid, partial, paid) is derived from payment_allocations of payments that are not void."),
    T(name="invoice_items", domain="billing", rls="clinic", star=True, lifecycle="finalizable",
      purpose="Lines on a bill, each optionally tied to a price item or procedure. GST is computed per line at issue.",
      cols=["invoice_id uuid -> invoices", "line_no smallint", "price_item_id uuid? -> price_items",
            "procedure_id uuid? -> procedures",
            "description text", "sac_hsn text?", "category text?", "quantity int", "unit_price_paise bigint",
            "discount_paise bigint", "tax_rate_bps int", "taxable_paise bigint", "cgst_paise bigint",
            "sgst_paise bigint", "igst_paise bigint", "total_paise bigint"],
      notes="Lines change only while the bill is a draft."),
    T(name="payments", domain="billing", rls="clinic", star=True, lifecycle="finalizable",
      purpose="Money received from a patient, by any method.",
      cols=["number text | receipt RC/26-27/000042", "patient_id uuid -> patients", "received_at timestamptz",
            "amount_paise bigint", "method payment_method | cash, upi, card, bank",
            "reference text? | UPI ref, card slip", "received_by uuid -> memberships",
            "idempotency_key text | unique per clinic; a retry returns the first payment",
            "request_hash text | a reused key with a different request is refused",
            "status payment_status | received, void", "void_reason text?", "voided_at timestamptz?",
            "voided_by uuid? -> memberships"]),
    T(name="payment_allocations", domain="billing", rls="clinic", star=True, lifecycle="append_only",
      purpose="Which bills a payment pays, so advances and partial payments work.",
      cols=["payment_id uuid -> payments", "invoice_id uuid -> invoices",
            "patient_id uuid -> patients | must match both the payment's and the bill's",
            "amount_paise bigint"],
      notes="A trigger refuses allocations past the bill's balance or the payment's amount, and to bills that are not issued."),
    T(name="refunds", domain="billing", rls="clinic",
      purpose="Money returned to a patient.",
      cols=["payment_id uuid -> payments", "amount_paise bigint", "reason text",
            "refunded_at timestamptz", "method payment_method"]),
    T(name="expense_categories", domain="billing", rls="clinic",
      purpose="Rent, electricity, salaries, consumables and so on.",
      cols=["name text"]),
    T(name="expenses", domain="billing", rls="clinic",
      purpose="Money the clinic spends.",
      cols=["branch_id uuid -> branches", "category_id uuid -> expense_categories",
            "amount_paise bigint", "paid_at date", "method payment_method", "vendor text?",
            "notes text?", "receipt_asset_id uuid? -> assets"]),
    T(name="daily_closings", domain="billing", rls="clinic",
      purpose="End-of-day cash count against what the system expects.",
      cols=["branch_id uuid -> branches", "day date", "cash_expected_paise bigint",
            "cash_counted_paise bigint", "closed_by uuid -> memberships", "closed_at timestamptz"]),

    # ------------------------------------------------------------------ notify
    T(name="message_templates", domain="notify", rls="clinic",
      purpose="Message text per channel and language. Clinic rows override platform defaults.",
      cols=["key text | appointment_reminder, birthday, recall_cleaning ...",
            "channel channel | whatsapp, sms, email, push", "language text", "body text",
            "category message_category | transactional, promotional",
            "provider_template_id text? | Meta or DLT template id",
            "approval approval_status | draft, pending, approved, rejected"],
      notes="org_id is null for platform defaults; this table allows that."),
    T(name="notification_rules", domain="notify", rls="clinic",
      purpose="When to message: on an event, before an appointment, on birthdays, on recalls.",
      cols=["trigger rule_trigger | event, before_appointment, birthday, recall",
            "event_key text? | booking.confirmed, invoice.paid ...",
            "offset_minutes int? | e.g. -1440 for a day before", "template_key text",
            "channels channel[] | in order of preference", "conditions jsonb?", "active bool"]),
    T(name="contact_preferences", domain="notify", rls="clinic",
      purpose="Per patient and channel: may we message them, and was promotional consent given?",
      cols=["patient_id uuid -> patients", "channel channel", "transactional_ok bool",
            "promotional_ok bool", "consented_at timestamptz?", "consent_source text?",
            "opted_out_at timestamptz?"],
      notes="Primary key (org_id, patient_id, channel)."),
    T(name="recalls", domain="notify", rls="clinic", lifecycle="mutable",
      purpose="Follow-ups that are due: cleaning in six months, BP review, vaccine.",
      cols=["patient_id uuid -> patients", "kind text | follow_up, cleaning, bp_review, vaccine",
            "reason text", "due_on date", "status recall_status | due, notified, booked, done, dismissed",
            "done_at timestamptz?",
            "source_procedure_id uuid? -> procedures"]),
    T(name="audiences", domain="notify", rls="clinic",
      purpose="Saved patient filters for campaigns: age, sex, treatment, doctor, fees, history.",
      cols=["name text", "filter jsonb", "estimated_count int?"]),
    T(name="campaigns", domain="notify", rls="clinic",
      purpose="A one-off or scheduled send to an audience: health tips, offers.",
      cols=["name text", "audience_id uuid -> audiences", "template_id uuid -> message_templates",
            "scheduled_at timestamptz?", "status campaign_status | draft, scheduled, sending, sent, cancelled",
            "cost_estimate_paise bigint?"]),
    T(name="promo_codes", domain="notify", rls="clinic",
      purpose="Discount codes a clinic can share.",
      cols=["code text | unique per clinic", "kind discount_kind | percent_bps, fixed", "value bigint",
            "valid_from date", "valid_to date?", "max_uses int?", "used_count int",
            "applies_to jsonb? | price items or categories"]),
    T(name="promo_redemptions", domain="notify", rls="clinic",
      purpose="Each use of a promo code on a bill.",
      cols=["promo_code_id uuid -> promo_codes", "patient_id uuid -> patients",
            "invoice_id uuid -> invoices", "discount_paise bigint", "redeemed_at timestamptz"]),
    T(name="outbox_events", domain="notify", rls="clinic", star=True, lifecycle="ephemeral",
      purpose="Messages to send because of a change, written in the same transaction as the change, for the worker to deliver.",
      cols=["event_key text | staff.invited; later appointment.booked, invoice.paid",
            "channel channel | email for now",
            "recipient text? | a staff address; patient messages will carry the patient's id in the payload",
            "payload jsonb | ids and non-patient template values, never patient details",
            "secret text? | a one-time link secret, cleared once sent or abandoned",
            "status outbox_status | pending, sent, failed",
            "attempts int", "next_attempt_at timestamptz | when due, or when a worker's lease ends",
            "last_error text? | short reason, no message content", "provider text? | log, resend",
            "provider_message_id text?", "processed_at timestamptz?"],
      notes="Guarantees a message is never lost or sent for a change that rolled back. The worker claims due rows across clinics with FOR UPDATE SKIP LOCKED through app.outbox_claim, retries with backoff, gives up after 5 attempts, and deletes rows 30 days after processing."),
    T(name="messages", domain="notify", rls="clinic", partitioned=True,
      purpose="Every message scheduled or sent, with its outcome and cost.",
      cols=["patient_id uuid? -> patients", "user_id uuid? -> users", "channel channel",
            "template_id uuid -> message_templates", "rule_id uuid? -> notification_rules",
            "campaign_id uuid? -> campaigns", "scheduled_for timestamptz",
            "status message_status | scheduled, queued, sent, delivered, read, failed, skipped",
            "skip_reason skip_reason? | no_consent, quiet_hours, duplicate, quota",
            "dedupe_key text | unique, e.g. reminder:appt-id:24h", "provider text?",
            "provider_message_id text?", "cost_paise bigint?", "sent_at timestamptz?"]),
    T(name="message_events", domain="notify", rls="clinic", partitioned=True,
      purpose="Delivery receipts from providers: sent, delivered, read, failed.",
      cols=["message_id uuid -> messages", "kind text", "at timestamptz", "details jsonb?"]),
    T(name="notifications", domain="notify", rls="clinic",
      purpose="The in-app notification feed for staff.",
      cols=["user_id uuid -> users", "kind text", "title text", "entity_ref jsonb | type and id to open",
            "read_at timestamptz?"]),

    # ------------------------------------------------------------------ web
    T(name="sites", domain="web", rls="clinic",
      purpose="A clinic's generated website: template family, repository and live version.",
      cols=["family text | template family key", "template_version text",
            "repo_full_name text? | sakalyatechnologies/site-smilecatchers",
            "status site_status | draft, building, live, failed", "config jsonb | from onboarding answers",
            "live_version_id uuid? -> site_versions"]),
    T(name="clinic_websites", domain="web", rls="clinic",
      purpose="A clinic's public website settings: layout, template, palette, fonts, owner-written content, published flag, custom domain.",
      cols=["layout text | one, multi", "template text | aurora, hearth, clinical, bold", "palette text | per template",
            "fonts text | font pairing", "content jsonb | section text, doctor profiles, hidden services, reviews",
            "published bool", "published_at timestamptz?", "custom_domain text? | claimed globally only once verified, in org_domains",
            "domain_status text | none, pending, verified, failed", "domain_token text? | TXT record value",
            "domain_checked_at timestamptz?"],
      notes="Primary key (org_id): one row per clinic. Public content only."),
    T(name="clinic_setup", domain="web", rls="clinic",
      purpose="Where the clinic stands in the first-run setup wizard: practice size, step statuses, dismissed or completed.",
      cols=["practice text? | solo, team, multi", "steps jsonb | step key -> done, skipped",
            "dismissed_at timestamptz?", "completed_at timestamptz?"],
      notes="Primary key (org_id): one row per clinic. Clinics that existed before the wizard are dismissed."),
    T(name="member_setup", domain="web", rls="clinic",
      purpose="Where an invited doctor stands in their one-screen setup.",
      cols=["membership_id uuid -> memberships", "steps jsonb | step key -> done, skipped",
            "dismissed_at timestamptz?", "completed_at timestamptz?"],
      notes="Primary key (org_id, membership_id)."),
    T(name="website_photos", domain="web", rls="clinic", lifecycle="ephemeral",
      purpose="Pictures on the website: logo, hero, about, doctors, gallery. Bytes are in file storage.",
      cols=["kind text | logo, hero, about, doctor, gallery", "storage_key text | <org_id>/<id>",
            "mime_type text | image/jpeg, image/png, image/webp", "size_bytes bigint", "sha256 text", "alt text?",
            "sort_order int"]),
    T(name="site_versions", domain="web", rls="clinic",
      purpose="Each publish of a site, so any version can be restored.",
      cols=["site_id uuid -> sites", "config jsonb", "commit_sha text?",
            "build_status build_status | queued, building, succeeded, failed", "built_at timestamptz?",
            "deployed_url text?"]),
    T(name="booking_requests", domain="web", rls="clinic",
      purpose="Booking requests from the website, before they become appointments.",
      cols=["site_id uuid -> sites", "name text", "phone_e164 text", "practitioner_id uuid? -> practitioners",
            "preferred_at timestamptz?", "message text?", "status booking_status | new, contacted, booked, spam",
            "appointment_id uuid? -> appointments"]),
    T(name="site_daily_stats", domain="web", rls="clinic",
      purpose="Website visits and bookings per day, for the clinic and the console.",
      cols=["day date", "visits int", "unique_visitors int", "booking_requests int"],
      notes="Primary key (org_id, day). Imported from Cloudflare Web Analytics."),

    # ------------------------------------------------------------------ trust
    T(name="consents", domain="trust", rls="user",
      purpose="A patient's permission for a clinic or doctor to see records held elsewhere, for a purpose and time.",
      cols=["patient_link_id uuid -> patient_links", "grantee_org_id uuid -> organizations",
            "grantee_practitioner_id uuid? -> practitioners",
            "purpose consent_purpose | care, referral, insurance",
            "data_categories text[] | e.g. prescriptions, dental, lab_reports",
            "source consent_source | patient_app, clinic, abdm",
            "starts_at timestamptz", "expires_at timestamptz?", "revoked_at timestamptz?"],
      notes="Every grant and revocation is audited. The clinic owns its record; the patient controls sharing across clinics."),
    T(name="share_links", domain="trust", rls="clinic", star=True, lifecycle="mutable",
      purpose="Expiring links that let a patient open a prescription, bill or report on the clinic's host.",
      cols=["token_hash text | the link holds a 256-bit token; only its hash is stored",
            "pin_hash text | SHA-256 of token and the six-digit PIN printed on the paper",
            "resource share_resource | prescription, invoice, report, upload_request",
            "prescription_id uuid? -> prescriptions", "invoice_id uuid? -> invoices",
            "patient_id uuid -> patients", "channel channel | whatsapp, sms, email, print",
            "failed_attempts int | five wrong PINs lock the link", "locked_at timestamptz?",
            "expires_at timestamptz | seven days", "opened_at timestamptz?", "open_count int",
            "revoked_at timestamptz?"],
      notes="Typed, tenant-aware foreign keys instead of a generic resource id: a check constraint requires exactly the column matching resource, so a link can only ever open a record of the same clinic and patient. Every open is written to access_log with purpose patient_self."),
    T(name="access_log", domain="trust", rls="clinic", star=True, partitioned=True,
      lifecycle="append_only", schema="audit",
      purpose="The access record: who opened which patient record, why, when and from which device. Patients can see it.",
      cols=["actor_user_id uuid? | null when a patient opens a share link",
            "actor_kind actor_kind | staff, patient, support",
            "patient_id uuid", "share_link_id uuid? | when opened through a share link",
            "resource access_resource | chart, note, attachment, prescription, invoice, export",
            "resource_id uuid?", "action access_action | view, download, print, share, export",
            "purpose access_purpose | care, front_desk, billing, support, patient_self, export",
            "device_id uuid?", "at timestamptz", "request_id text?"],
      notes="Primary key (org_id, at, id), partitioned by month. No foreign keys, so the ledger never blocks erasure and adds no lock cost; the ids refer to users, patients, devices and share_links. Append-only: the app role can insert but never update or delete. Views made offline are queued on the device and uploaded."),
    T(name="audit_events", domain="trust", rls="clinic", star=True, partitioned=True,
      lifecycle="append_only", schema="audit",
      purpose="The change history: every insert, update and delete, written by triggers.",
      cols=["table_name text", "row_id uuid", "action audit_action | insert, update, delete",
            "actor_user_id uuid?", "actor_kind text? | staff, patient, support, system",
            "changes jsonb? | changed columns only, as {column: [old, new]}, masked per audit_config",
            "at timestamptz", "request_id text?"],
      notes="Primary key (id, at), partitioned by month; org_id is null for platform tables. Written by app.audit_row(), which skips updates that change nothing and records only metadata for inserts into append-only tables. No foreign keys."),
    T(name="audit_config", domain="trust", rls="global", star=True, lifecycle="mutable", schema="audit",
      purpose="Per table: which columns the audit trigger leaves out or masks.",
      cols=["table_name text | unique, schema-qualified", "exclude text[] | not recorded, e.g. last_seen_at",
            "mask text[] | recorded as changed with the value hashed, e.g. pin_hash",
            "metadata_only bool | record only that the row changed"]),
    T(name="data_requests", domain="trust", rls="clinic",
      purpose="Patients' DPDP requests: export, correction, erasure.",
      cols=["patient_id uuid -> patients", "kind data_request_kind | export, correction, erasure",
            "status request_status | received, in_progress, done, rejected", "requested_at timestamptz",
            "completed_at timestamptz?", "notes text?"]),

    # ------------------------------------------------------------------ onboarding
    T(name="onboarding_progress", domain="onboarding", rls="clinic",
      purpose="Where a new clinic is in the first-login wizard, and its answers.",
      cols=["steps jsonb | step key to answers", "completed_at timestamptz?"],
      notes="One row per clinic."),
    T(name="imports", domain="onboarding", rls="clinic", lifecycle="append_only",
      purpose="A data import from a CSV or Excel file.",
      cols=["kind import_kind | patients", "source text | csv, xlsx",
            "mapping jsonb | our field to the file's column", "status import_status | done, failed",
            "total_rows int", "imported_rows int", "failed_rows int",
            "skipped_rows int | duplicates left out", "merged_rows int | duplicates merged into an existing record",
            "incomplete_rows int | imported with details missing",
            "session_id uuid? -> import_sessions | unique: committing a session twice finds this import",
            "file_name text? | as uploaded", "sheet_name text? | the workbook sheet read"],
      notes="Smart import (CSV or .xlsx via import_sessions) records file, sheet and each row; the older CSV-text endpoint records only the mapping. Appointments and invoices are planned."),
    T(name="import_rows", domain="onboarding", rls="clinic", lifecycle="append_only",
      purpose="Each row of an import with its result: the source reference (file and sheet on the import, row here) of every imported record.",
      cols=["import_id uuid -> imports", "row_number int | row in the file, header row counted",
            "raw jsonb | the row's mapped values (CSV-text imports); empty for smart imports, whose rows live only in the session",
            "status row_status | imported, failed, skipped, merged", "error text? | why it failed or was skipped",
            "patient_id uuid? -> patients | the patient it became or was merged into"]),
    T(name="import_sessions", domain="onboarding", rls="clinic", lifecycle="mutable",
      purpose="An uploaded file being mapped and previewed before import. Holds the parsed rows, never the file.",
      cols=["file_name text", "file_kind text | csv, xlsx", "file_sha256 text", "size_bytes int | at most 5 MB",
            "sheet_names text[] | a workbook's sheets", "sheet_name text?", "header_row int | found automatically below any title rows",
            "headers text[]", "cells jsonb? | the data rows; cleared on commit, discard or expiry, excluded from the audit log",
            "row_count int | at most 5,000", "status text | open, committed, discarded, expired",
            "import_id uuid? -> imports", "expires_at timestamptz | 24 hours after upload"],
      notes="Expired sessions are ended, and their cells cleared, when the clinic next uploads."),
    T(name="import_column_memory", domain="onboarding", rls="clinic", lifecycle="mutable",
      purpose="Which field each column header meant last time, so the clinic's next file maps itself.",
      cols=["header_key text | unique per clinic: the header in lower case, punctuation as spaces",
            "field text | full_name, sex, date_of_birth, age_years, phone, email, preferred_language, file_number, legacy_id, address, last_visit, balance"]),
    T(name="patient_gaps", domain="onboarding", rls="clinic", lifecycle="mutable",
      purpose="The front desk's to-do list: patients imported without some details.",
      cols=["patient_id uuid -> patients", "import_id uuid -> imports", "row_number int | their row in the file",
            "missing text[] | phone, sex, date_of_birth, as imported", "dismissed_at timestamptz?", "dismissed_by uuid?"],
      notes="What is still missing is worked out from the patient's current record, so filling a detail clears it; dismissing says the details can't be had."),
]

# How tables are used together. Each step: (who or what, tables touched, what happens).
JOURNEYS = [
    ("onboard", "A new clinic signs up", [
        ("Sakalya console", ["organizations", "org_domains", "subscriptions"], "Clinic created on a trial plan with its subdomain."),
        ("Owner", ["invitations", "users", "memberships", "roles"], "Owner accepts the invite and becomes a member with the owner role."),
        ("Wizard", ["onboarding_progress", "org_modules", "org_settings", "price_items", "working_hours", "practitioners"], "Specialty, branding, prices and hours set up from defaults."),
        ("Website", ["sites", "site_versions", "org_domains"], "Site generated from answers, repository created, built and deployed."),
        ("Import", ["import_sessions", "import_column_memory", "imports", "import_rows", "patients", "patient_identifiers", "patient_gaps"], "The clinic's CSV or Excel file mapped automatically, previewed and imported, keeping file numbers; patients missing details go on the front desk's to-do list."),
    ]),
    ("visit", "A patient visits the dentist", [
        ("Front desk", ["patients", "patient_identifiers", "referral_sources", "number_sequences"], "New patient registered as SC-1042, or found by name, phone or ID."),
        ("Front desk", ["appointments", "appointment_events", "queue_tokens"], "Appointment marked arrived; token shown on the waiting screen."),
        ("Assistant", ["encounters", "observations", "clinical_notes"], "Visit opened; vitals and intake note recorded."),
        ("Doctor", ["voice_notes", "attachments", "specialty_records", "clinical_notes", "access_log"], "Dictates a note, adds an X-ray, updates the tooth chart; every view is logged."),
        ("Doctor", ["procedures", "stock_movements", "lab_orders", "prescriptions", "prescription_items"], "Root canal done on tooth 36: stock deducted, crown sent to the lab, prescription issued."),
        ("Doctor", ["document_templates", "share_links", "access_log"], "Prescription printed on the clinic letterhead with the Aarogyam footer and QR; the patient gets an expiring WhatsApp link."),
        ("Front desk", ["invoices", "invoice_items", "payments", "payment_allocations"], "Bill SC/26-27/000318 issued and paid by UPI."),
        ("System", ["outbox_events", "messages", "recalls", "audit_events"], "Receipt sent on WhatsApp, a follow-up recall created, all changes audited."),
    ]),
    ("remind", "Reminders, birthdays and recalls", [
        ("Rules", ["notification_rules", "message_templates"], "Clinic has reminder, birthday and recall rules switched on."),
        ("Scheduler", ["appointments", "patients", "recalls", "messages"], "Due messages created with a dedupe key, e.g. reminder:appt:24h."),
        ("Worker", ["contact_preferences", "usage_counters", "messages"], "Consent, quiet hours and quota checked; message sent or skipped with a reason."),
        ("Provider", ["message_events", "messages"], "Delivery and read receipts recorded; cost metered per clinic."),
    ]),
    ("finance", "Month-end finance report", [
        ("Money in", ["payments", "refunds", "payment_allocations", "invoices"], "Collections by doctor, treatment, referral source and payment method."),
        ("Money out", ["expenses", "lab_payments", "payroll_entries", "consultant_payouts"], "Spending by category, lab, staff and consultant."),
        ("Report", ["daily_closings"], "A ledger view joins both sides; exported to Excel by the worker."),
    ]),
    ("access", "A request checks access", [
        ("Host", ["org_domains", "organizations"], "smilecatchers.aarogyam.example resolves to the clinic."),
        ("Session", ["users", "sessions"], "JWT verified, session still active."),
        ("Membership", ["memberships", "roles", "role_permissions"], "User is an active member whose role allows patients.read."),
        ("Plan and flags", ["subscriptions", "plan_features", "entitlement_overrides", "feature_flags", "flag_rules"], "Feature is in the plan and released to this clinic."),
        ("Database", ["patients"], "Row-level security limits every query to this clinic."),
    ]),
    ("patient", "Phase 3: a patient sees all their clinics", [
        ("Patient", ["users", "patient_links"], "Patient signs in with their phone and verifies records at each clinic."),
        ("Patient", ["consents"], "Patient lets their new cardiologist see their dental and GP records."),
        ("Cardiologist", ["encounters", "prescriptions", "attachments", "access_log"], "Reads the shared records; the patient sees who looked."),
    ]),
]

# Data sensitivity drives logging, analytics, export, support access, retention and AI rules.
#   public       shown on websites            internal   clinic configuration
#   personal     contact and identity data    financial  bills and payments
#   health       clinical data (PHI)
SENSITIVITY_BY_DOMAIN = {
    "platform": "internal", "iam": "personal", "tenancy": "internal", "people": "personal",
    "scheduling": "personal", "clinical": "health", "ops": "internal", "billing": "financial",
    "notify": "personal", "web": "public", "trust": "health", "onboarding": "personal",
}
SENSITIVITY_OVERRIDES = {
    "medical_history_items": "health", "patient_links": "health", "drug_catalog": "public",
    "document_templates": "internal", "lab_orders": "health", "consent_forms": "health",
    "booking_requests": "personal", "payroll_entries": "financial", "salary_structures": "financial",
    "staff_advances": "financial", "consultant_payouts": "financial", "lab_payments": "financial",
    "saas_invoices": "financial", "org_daily_stats": "internal", "site_daily_stats": "internal",
    "audit_events": "health", "audit_config": "internal", "assets": "internal", "number_sequences": "internal",
    "price_items": "internal", "expense_categories": "internal", "drug_interactions": "public",
}

# What the phone apps may do offline. Everything not listed is server-only: written only by the
# API, never created on a device (bill and prescription numbers, payments, audit, permissions).
OFFLINE_READ_WRITE = [
    "patients", "patient_identifiers", "medical_history_items", "appointments", "appointment_events",
    "queue_tokens", "encounters", "clinical_notes", "note_addenda", "observations", "conditions", "allergies",
    "procedures", "prescriptions", "prescription_items", "attachments", "voice_notes",
    "specialty_records",
]
OFFLINE_READ_ONLY = [
    "organizations", "branches", "rooms", "org_settings", "org_modules", "roles", "role_permissions",
    "memberships", "membership_branches", "practitioners", "working_hours", "price_items", "drug_catalog",
    "document_templates", "referral_sources", "message_templates", "drug_interactions",
]
