"""Arogyam database design: the single source for docs/database.md and the schema explorer.

Edit this file, then run `python3 scripts/gen_schema_docs.py`.

Column syntax: "name type[?] [-> table] [| note]"
  ?          the column is nullable
  -> table   foreign key (clinic tables also include org_id in the key)
  | note     short explanation

Every table with rls="clinic" also has, without listing them here:
  org_id uuid -> organizations, id uuid (primary key is (org_id, id)),
  created_at, created_by, updated_at, updated_by, and deleted_at where soft-deletable.
Tables with rls="global" have id uuid as primary key plus created_at / updated_at.
"""

DOMAINS = [
    ("platform", "Platform", "Run by Sakalya: plans, billing clinics, feature rollout, support, platform analytics. Console only."),
    ("iam", "Identity", "People who sign in, their sessions and devices. One user can belong to many clinics."),
    ("tenancy", "Clinic setup", "The clinic itself: branches, domains, rooms, modules, roles, staff memberships, numbering."),
    ("people", "Patients and doctors", "Each clinic's own patient records, identifiers, families, referral sources and practitioners."),
    ("scheduling", "Scheduling", "Appointments, their history, and the walk-in token queue."),
    ("clinical", "Clinical", "Visits, notes, vitals, diagnoses, prescriptions, procedures, treatment plans, files and specialty data."),
    ("ops", "Clinic operations", "Lab work, inventory and stock, equipment maintenance, payroll and consultant fees."),
    ("billing", "Money", "Price list, bills, payments, refunds, expenses and daily cash closing."),
    ("notify", "Notifications", "Templates, rules, consent, recalls, campaigns, promo codes, the outbox and every message sent."),
    ("web", "Websites", "Generated clinic websites, their versions, booking requests and traffic."),
    ("trust", "Trust and audit", "Patient consents, who viewed what, every change, and data-rights requests."),
    ("onboarding", "Onboarding", "First-login progress and data imports from old software."),
]

T = dict  # readability alias

TABLES = [
    # ------------------------------------------------------------------ platform
    T(name="plans", domain="platform", rls="global", star=True,
      purpose="Subscription plans clinics can buy (Solo, Clinic, Pro, Enterprise).",
      cols=["code text | unique: solo, clinic, pro, enterprise", "name text",
            "monthly_price_paise bigint", "yearly_price_paise bigint",
            "is_public bool | hidden plans for custom deals", "sort_order int"]),
    T(name="features", domain="platform", rls="global", star=True,
      purpose="Every feature that a plan can include or limit.",
      cols=["key text | unique, e.g. website_builder, whatsapp_campaigns", "name text",
            "kind feature_kind | boolean or limit", "description text"]),
    T(name="plan_features", domain="platform", rls="global", star=True,
      purpose="What each plan includes, and its limits.",
      cols=["plan_id uuid -> plans", "feature_id uuid -> features", "included bool",
            "limit_value int? | e.g. 2000 messages a month"],
      notes="Primary key (plan_id, feature_id)."),
    T(name="subscriptions", domain="platform", rls="global", star=True,
      purpose="Which plan a clinic is on and whether it is paid up.",
      cols=["org_id uuid -> organizations", "plan_id uuid -> plans",
            "status subscription_status | trialing, active, past_due, paused, canceled",
            "period_start date", "period_end date", "trial_ends_at timestamptz?",
            "razorpay_subscription_id text?", "canceled_at timestamptz?"]),
    T(name="saas_invoices", domain="platform", rls="global",
      purpose="Sakalya's own GST invoices to clinics for the subscription.",
      cols=["org_id uuid -> organizations", "subscription_id uuid -> subscriptions",
            "number text | Sakalya's invoice series", "amount_paise bigint", "gst_paise bigint",
            "status saas_invoice_status | issued, paid, void", "razorpay_payment_id text?",
            "issued_at timestamptz"]),
    T(name="entitlement_overrides", domain="platform", rls="global",
      purpose="Per-clinic exceptions to the plan: promos, grandfathering, custom deals.",
      cols=["org_id uuid -> organizations", "feature_id uuid -> features", "included bool",
            "limit_value int?", "reason text", "expires_at timestamptz?",
            "granted_by uuid -> platform_users"]),
    T(name="usage_counters", domain="platform", rls="global",
      purpose="How much of each limited feature a clinic used this month.",
      cols=["org_id uuid -> organizations", "feature_id uuid -> features",
            "period date | first day of the month", "used bigint"],
      notes="Primary key (org_id, feature_id, period). Incremented by the API and worker."),
    T(name="feature_flags", domain="platform", rls="global", star=True,
      purpose="Switches that release a feature gradually, separate from plans.",
      cols=["key text | unique", "description text", "default_on bool",
            "kill_switch bool | forces off everywhere"]),
    T(name="flag_rules", domain="platform", rls="global",
      purpose="Who a flag is on for: named clinics, a percentage, a plan, a platform or app version.",
      cols=["flag_id uuid -> feature_flags",
            "kind flag_rule_kind | org_list, percentage, plan, platform, min_app_version",
            "value jsonb", "priority int"]),
    T(name="platform_users", domain="platform", rls="global",
      purpose="Sakalya staff who can use the console, and their role.",
      cols=["user_id uuid -> users", "role platform_role | owner, support, onboarding, analyst",
            "active bool"]),
    T(name="support_grants", domain="platform", rls="global",
      purpose="Time-limited permission a clinic gives Sakalya support to look inside its data.",
      cols=["org_id uuid -> organizations", "granted_by uuid -> users",
            "platform_user_id uuid? -> platform_users | null means any support agent",
            "scope support_scope | settings_only, read_records", "starts_at timestamptz",
            "expires_at timestamptz", "revoked_at timestamptz?"]),
    T(name="announcements", domain="platform", rls="global",
      purpose="Release notes and notices shown inside the clinic apps.",
      cols=["title text", "body text", "audience jsonb | plans, roles, platforms",
            "starts_at timestamptz", "ends_at timestamptz?"]),
    T(name="org_daily_stats", domain="platform", rls="global",
      purpose="Per-clinic daily counts for the console. Counts only, never patient data.",
      cols=["org_id uuid -> organizations", "day date", "active_users int", "new_patients int",
            "appointments int", "visits int", "billed_paise bigint", "messages_sent int",
            "storage_bytes bigint"],
      notes="Primary key (org_id, day). Written nightly, copied to BigQuery."),

    T(name="quality_runs", domain="platform", rls="global",
      purpose="One run of a test suite: CI unit and integration, end-to-end, canary or load test.",
      cols=["suite test_suite | unit, integration, e2e_web, e2e_mobile, canary, load",
            "environment text | ci, staging, production", "repository text", "commit_sha text?",
            "branch text?", "trigger run_trigger | push, pull_request, schedule, deploy, manual",
            "status run_status | running, passed, failed, cancelled", "started_at timestamptz",
            "finished_at timestamptz?", "total int", "passed int", "failed int", "skipped int",
            "flaky int | passed only on retry", "run_url text? | link to the CI job"],
      notes="Written by CI (JUnit upload) and the canary runner through the console API."),
    T(name="quality_results", domain="platform", rls="global",
      purpose="Each test or canary step in a run, with its outcome and timing.",
      cols=["run_id uuid -> quality_runs", "test_name text", "file text?",
            "status result_status | passed, failed, skipped, flaky", "duration_ms int",
            "attempts smallint", "error_message text? | trimmed, no patient data",
            "request_id text? | canary steps: open with sk request"],
      notes="Partition or prune after 90 days; the console keeps daily aggregates."),
    T(name="canary_checks", domain="platform", rls="global",
      purpose="The canary journeys that run on a schedule, per environment.",
      cols=["key text | sign_in, book_appointment, write_note, issue_bill", "description text",
            "environment text | staging, production", "interval_minutes int", "enabled bool",
            "last_run_id uuid? -> quality_runs"]),

    # ------------------------------------------------------------------ iam
    T(name="users", domain="iam", rls="user", star=True,
      purpose="Anyone who signs in: staff, doctors, patients, Sakalya staff.",
      cols=["auth_uid uuid | Supabase Auth user id, unique", "phone_e164 text? | unique",
            "email text?", "display_name text", "locale text | en-IN, hi-IN, mr-IN ...",
            "status user_status | active, disabled", "last_seen_at timestamptz?"]),
    T(name="sessions", domain="iam", rls="user", star=True,
      purpose="Signed-in sessions, so a stolen phone or idle PC can be signed out.",
      cols=["user_id uuid -> users", "provider_session_id uuid | session_id claim in the JWT",
            "device_id uuid? -> devices", "audience session_audience | clinic, patient, platform",
            "last_active_at timestamptz", "expires_at timestamptz", "revoked_at timestamptz?",
            "revoke_reason text?"]),
    T(name="devices", domain="iam", rls="user", star=True,
      purpose="Phones and browsers a user signs in from, with push tokens.",
      cols=["user_id uuid -> users", "platform device_platform | android, ios, web",
            "model text?", "app_version text?", "push_token text?",
            "push_token_updated_at timestamptz?"]),

    # ------------------------------------------------------------------ tenancy
    T(name="organizations", domain="tenancy", rls="global", star=True,
      purpose="A clinic business, the tenant. Everything clinic-owned points here.",
      cols=["slug text | unique, the subdomain: smilecatchers", "name text", "legal_name text?",
            "number_prefix text | SC in SC-1042", "status org_status | trial, active, suspended, churned",
            "timezone text | default Asia/Kolkata", "gstin text?"]),
    T(name="branches", domain="tenancy", rls="clinic", star=True,
      purpose="Locations of a clinic. Single-location clinics have one.",
      cols=["slug text | unique per clinic", "name text", "address jsonb", "phone_e164 text?",
            "is_default bool"]),
    T(name="org_domains", domain="tenancy", rls="global", star=True,
      purpose="Host names that resolve to a clinic: its portal and its website.",
      cols=["org_id uuid -> organizations",
            "hostname text | unique: smilecatchers.arogyam.app, smilecatchers.in",
            "kind domain_kind | portal, website", "is_primary bool",
            "cloudflare_hostname_id text?", "verified_at timestamptz?"],
      notes="Read on every request to resolve the tenant; cached in memory."),
    T(name="slug_history", domain="tenancy", rls="global",
      purpose="Old slugs, so renamed clinics, doctors and pages keep redirecting.",
      cols=["entity slug_entity | organization, practitioner, site_page", "entity_id uuid",
            "old_slug text", "changed_at timestamptz"]),
    T(name="rooms", domain="tenancy", rls="clinic",
      purpose="Chairs, rooms and labs that appointments can be booked into.",
      cols=["branch_id uuid -> branches", "name text", "kind room_kind | chair, room, lab",
            "active bool"]),
    T(name="org_modules", domain="tenancy", rls="clinic",
      purpose="Specialty modules switched on for a clinic, with their settings.",
      cols=["module_key text | dental, general, obstetrics, pediatrics ...", "enabled_at timestamptz",
            "settings jsonb | e.g. tooth numbering FDI or Universal"]),
    T(name="org_settings", domain="tenancy", rls="clinic", star=True,
      purpose="One row per clinic: branding, bill and prescription settings, defaults.",
      cols=["branding jsonb | colours, logo asset", "billing jsonb | GST, bill footer",
            "prescription jsonb | letterhead layout", "notifications jsonb | quiet hours, sender"]),
    T(name="assets", domain="tenancy", rls="clinic",
      purpose="Non-medical files: logos, signatures, generated PDFs, website images.",
      cols=["kind asset_kind | logo, signature, pdf, site_image", "storage_key text",
            "mime_type text", "size_bytes bigint"],
      notes="Stored in a different bucket from patient attachments."),
    T(name="roles", domain="tenancy", rls="clinic", star=True,
      purpose="Named bundles of permissions. Seeded from templates; owners can add their own.",
      cols=["key text | owner, doctor, consultant, finance, front_desk, assistant, or custom",
            "name text", "is_template bool", "description text?"]),
    T(name="role_permissions", domain="tenancy", rls="clinic", star=True,
      purpose="What a role may do: module.action plus a scope.",
      cols=["role_id uuid -> roles", "permission text | patients.read, finance.view, mask.patient_phone",
            "scope permission_scope | all, own, assigned"],
      notes="Primary key (org_id, role_id, permission)."),
    T(name="memberships", domain="tenancy", rls="clinic", star=True,
      purpose="A user's place in a clinic: role, branches, status. The link between users and clinics.",
      cols=["user_id uuid -> users", "role_id uuid -> roles",
            "status membership_status | invited, active, suspended, left",
            "branch_ids uuid[]? | null means all branches", "pin_hash text? | quick switch on shared PCs",
            "joined_at timestamptz?"]),
    T(name="invitations", domain="tenancy", rls="clinic", star=True,
      purpose="Pending invites to join a clinic.",
      cols=["phone_e164 text?", "email text?", "role_id uuid -> roles", "invited_by uuid -> users",
            "token_hash text", "expires_at timestamptz", "accepted_at timestamptz?"]),
    T(name="number_sequences", domain="tenancy", rls="clinic", star=True,
      purpose="Counters behind readable numbers: SC-1042, V-2026-0318, SC/26-27/000318.",
      cols=["kind sequence_kind | patient, visit, invoice, prescription, lab_order",
            "period text | financial year such as 26-27, or empty", "next_value bigint"],
      notes="Primary key (org_id, kind, period). Incremented with UPDATE ... RETURNING inside the same transaction."),

    # ------------------------------------------------------------------ people
    T(name="patients", domain="people", rls="clinic", star=True,
      purpose="A clinic's own record of a patient. Two clinics never share this row.",
      cols=["number text | SC-1042, unique per clinic, used in URLs", "full_name text",
            "sex sex | female, male, other, unknown", "date_of_birth date?",
            "age_estimate_years smallint? | when the date of birth is unknown",
            "phone_e164 text? | indexed", "alt_phone_e164 text?", "email text?", "address jsonb?",
            "preferred_language text", "blood_group blood_group?",
            "referral_source_id uuid? -> referral_sources",
            "referred_by_patient_id uuid? -> patients", "tags text[]",
            "status patient_status | active, inactive, deceased, merged",
            "merged_into_id uuid? -> patients", "last_visit_at timestamptz?"],
      notes="Name search uses a pg_trgm index. Duplicate warning on the same phone number."),
    T(name="patient_identifiers", domain="people", rls="clinic", star=True,
      purpose="Extra IDs for a patient: custom file number, smart card, ABHA, legacy import.",
      cols=["patient_id uuid -> patients",
            "kind identifier_kind | custom, smart_card, abha_number, abha_address, legacy",
            "value text"],
      notes="Unique (org_id, kind, value)."),
    T(name="family_links", domain="people", rls="clinic",
      purpose="Relationships between patients in the same clinic: parent, child, spouse, guardian.",
      cols=["patient_id uuid -> patients", "related_patient_id uuid -> patients",
            "relation relation_kind | parent, child, spouse, guardian, other",
            "can_manage bool | guardian may act for this patient"]),
    T(name="referral_sources", domain="people", rls="clinic", star=True,
      purpose="Where patients come from, for the finance and marketing filters.",
      cols=["name text", "kind referral_kind | patient, doctor, online, walk_in, camp, insurance, other",
            "active bool"]),
    T(name="medical_history_items", domain="people", rls="clinic",
      purpose="History captured at registration: conditions, surgeries, habits, family history.",
      cols=["patient_id uuid -> patients",
            "kind history_kind | condition, surgery, medication, habit, family_history",
            "description text", "code text? | ICD-10 or SNOMED when known", "since date?", "active bool"]),
    T(name="patient_links", domain="people", rls="user",
      purpose="Phase 3: connects a patient's own Arogyam account to their record at each clinic.",
      cols=["user_id uuid -> users", "org_id uuid -> organizations", "patient_id uuid -> patients",
            "verified_via link_method | otp, abha, clinic_confirmed", "verified_at timestamptz",
            "revoked_at timestamptz?"],
      notes="This is the single-umbrella view: one person, many clinic records, joined only by verified links."),
    T(name="practitioners", domain="people", rls="clinic", star=True,
      purpose="Doctors who see patients at the clinic, with registration and fees.",
      cols=["membership_id uuid -> memberships", "slug text | public page: dr-kiran-patil",
            "display_name text", "qualifications text",
            "council registration_council | nmc, state, dci, ayush ...", "registration_number text",
            "specialties text[] | module keys", "signature_asset_id uuid? -> assets",
            "default_fee_paise bigint", "is_visiting bool | visiting consultant", "calendar_color text"]),
    T(name="working_hours", domain="people", rls="clinic", star=True,
      purpose="Weekly hours per clinic or doctor. Split shifts are two rows.",
      cols=["practitioner_id uuid? -> practitioners | null means clinic hours",
            "branch_id uuid -> branches", "weekday smallint | 1 Monday to 7 Sunday",
            "starts time", "ends time", "valid_from date", "valid_to date?"]),
    T(name="leave_blocks", domain="people", rls="clinic",
      purpose="Time a doctor or branch is unavailable.",
      cols=["practitioner_id uuid? -> practitioners", "branch_id uuid? -> branches",
            "starts_at timestamptz", "ends_at timestamptz", "reason text?"]),

    # ------------------------------------------------------------------ scheduling
    T(name="appointments", domain="scheduling", rls="clinic", star=True,
      purpose="A booked slot with a doctor, optionally in a room or chair.",
      cols=["patient_id uuid -> patients", "practitioner_id uuid -> practitioners",
            "branch_id uuid -> branches", "room_id uuid? -> rooms", "starts_at timestamptz",
            "ends_at timestamptz",
            "status appointment_status | scheduled, confirmed, arrived, in_progress, completed, cancelled, no_show",
            "kind appointment_kind | new, follow_up, procedure, teleconsult", "reason text?",
            "source booking_source | front_desk, phone, website, app, whatsapp",
            "cancel_reason text?", "encounter_id uuid? -> encounters"],
      notes="An exclusion constraint on (org_id, practitioner_id, time range) stops double booking."),
    T(name="appointment_events", domain="scheduling", rls="clinic", star=True,
      purpose="Every status change of an appointment, for history and no-show reports.",
      cols=["appointment_id uuid -> appointments", "from_status appointment_status?",
            "to_status appointment_status", "at timestamptz", "note text?"]),
    T(name="queue_tokens", domain="scheduling", rls="clinic",
      purpose="Walk-in tokens shown on the waiting-room screen.",
      cols=["branch_id uuid -> branches", "day date", "token_number int",
            "patient_id uuid -> patients", "appointment_id uuid? -> appointments",
            "status token_status | waiting, called, in_room, done, skipped", "called_at timestamptz?"],
      notes="Unique (org_id, branch_id, day, token_number)."),

    # ------------------------------------------------------------------ clinical
    T(name="encounters", domain="clinical", rls="clinic", star=True,
      purpose="One visit: everything clinical from that day hangs off it.",
      cols=["number text | V-2026-0318", "patient_id uuid -> patients",
            "practitioner_id uuid -> practitioners", "branch_id uuid -> branches",
            "appointment_id uuid? -> appointments", "started_at timestamptz", "ended_at timestamptz?",
            "status encounter_status | open, closed", "chief_complaint text?"]),
    T(name="clinical_notes", domain="clinical", rls="clinic", star=True,
      purpose="Doctor and intake notes. Signed notes never change.",
      cols=["encounter_id uuid -> encounters", "patient_id uuid -> patients",
            "author_id uuid -> memberships",
            "kind note_kind | soap, progress, procedure, intake, front_desk",
            "body jsonb | sections: subjective, objective, assessment, plan",
            "source note_source | typed, voice, ai_draft", "status note_status | draft, signed",
            "signed_at timestamptz?", "signed_by uuid? -> memberships"],
      notes="Reading a note writes access_log. Corrections go in note_addenda."),
    T(name="note_addenda", domain="clinical", rls="clinic",
      purpose="Corrections and additions to a signed note, with their own author and time.",
      cols=["note_id uuid -> clinical_notes", "author_id uuid -> memberships", "body text"]),
    T(name="observations", domain="clinical", rls="clinic",
      purpose="Measurements: BP, pulse, temperature, SpO2, weight, height, sugar.",
      cols=["patient_id uuid -> patients", "encounter_id uuid? -> encounters",
            "kind observation_kind | bp_systolic, bp_diastolic, pulse, temperature, spo2, weight, height, blood_sugar ...",
            "value_num numeric", "unit text", "loinc_code text?", "recorded_at timestamptz"]),
    T(name="conditions", domain="clinical", rls="clinic",
      purpose="Diagnoses, coded where possible.",
      cols=["patient_id uuid -> patients", "encounter_id uuid? -> encounters",
            "code_system code_system | icd10, snomed, custom", "code text?", "label text",
            "status condition_status | active, resolved", "onset date?"]),
    T(name="allergies", domain="clinical", rls="clinic",
      purpose="Allergies, shown as a warning banner on the patient.",
      cols=["patient_id uuid -> patients", "substance text", "reaction text?",
            "severity severity | mild, moderate, severe", "active bool"]),
    T(name="drug_catalog", domain="clinical", rls="global",
      purpose="Shared list of medicines (brand, generic, strength) for quick prescribing.",
      cols=["brand_name text", "generic_name text", "strength text", "form drug_form | tablet, syrup, injection ...",
            "manufacturer text?"]),
    T(name="prescriptions", domain="clinical", rls="clinic",
      purpose="A prescription issued in a visit, printed or sent as a PDF.",
      cols=["number text | RX-0412", "encounter_id uuid -> encounters", "patient_id uuid -> patients",
            "practitioner_id uuid -> practitioners", "issued_at timestamptz?", "language text",
            "notes text?", "status rx_status | draft, issued, cancelled", "pdf_asset_id uuid? -> assets"]),
    T(name="prescription_items", domain="clinical", rls="clinic",
      purpose="One medicine on a prescription.",
      cols=["prescription_id uuid -> prescriptions", "drug_id uuid? -> drug_catalog",
            "drug_name text | as printed", "dose text", "frequency text | 1-0-1",
            "timing dose_timing | before_food, after_food, bedtime, sos", "duration_days smallint",
            "instructions text?"]),
    T(name="procedures", domain="clinical", rls="clinic",
      purpose="Treatment actually done (or planned for today), linked to the price list.",
      cols=["encounter_id uuid -> encounters", "patient_id uuid -> patients",
            "practitioner_id uuid -> practitioners", "price_item_id uuid -> price_items",
            "label text", "site jsonb? | specialty location, e.g. tooth 36, surfaces O and D",
            "status procedure_status | planned, done", "performed_at timestamptz?",
            "amount_paise bigint", "treatment_plan_item_id uuid? -> treatment_plan_items"],
      notes="Marking done deducts stock via procedure_materials and can create a lab_order."),
    T(name="treatment_plans", domain="clinical", rls="clinic",
      purpose="A proposed course of treatment with a cost estimate, accepted or declined by the patient.",
      cols=["patient_id uuid -> patients", "practitioner_id uuid -> practitioners", "title text",
            "status plan_status | proposed, accepted, in_progress, completed, declined",
            "estimate_paise bigint", "accepted_at timestamptz?"]),
    T(name="treatment_plan_items", domain="clinical", rls="clinic",
      purpose="Steps of a treatment plan, in phases.",
      cols=["plan_id uuid -> treatment_plans", "price_item_id uuid -> price_items", "label text",
            "site jsonb?", "phase smallint", "estimate_paise bigint",
            "status plan_item_status | pending, done, dropped"]),
    T(name="attachments", domain="clinical", rls="clinic", star=True,
      purpose="Patient files: photos, X-rays, reports, documents, audio, signed consent.",
      cols=["patient_id uuid -> patients", "encounter_id uuid? -> encounters",
            "kind attachment_kind | photo, xray, report, document, audio, consent",
            "storage_key text | private bucket", "mime_type text", "size_bytes bigint",
            "taken_at timestamptz?", "caption text?", "site jsonb? | e.g. tooth 36"],
      notes="Served only through short-lived signed URLs after a permission check."),
    T(name="voice_notes", domain="clinical", rls="clinic",
      purpose="A recorded note, its transcription status and the draft it produced.",
      cols=["attachment_id uuid -> attachments", "encounter_id uuid -> encounters",
            "duration_ms int", "language text",
            "transcript_status transcript_status | pending, processing, done, failed",
            "transcript text?", "draft_note_id uuid? -> clinical_notes"]),
    T(name="specialty_records", domain="clinical", rls="clinic", star=True,
      purpose="Specialty-specific data as versioned JSON: tooth chart, pregnancy, growth.",
      cols=["patient_id uuid -> patients", "encounter_id uuid? -> encounters",
            "module text | dental, obstetrics, pediatrics ...", "kind text | dental_chart, pregnancy, growth",
            "schema_version int", "data jsonb | validated against the module schema on write",
            "valid_from timestamptz"],
      notes="New rows supersede old ones, so the chart's history is kept."),
    T(name="document_templates", domain="clinical", rls="clinic",
      purpose="Consent forms, certificates and letter templates a clinic uses.",
      cols=["kind doc_template_kind | consent, certificate, letter", "name text",
            "body text | with placeholders", "module text?"]),
    T(name="consent_forms", domain="clinical", rls="clinic",
      purpose="A signed procedure consent.",
      cols=["patient_id uuid -> patients", "template_id uuid -> document_templates",
            "procedure_id uuid? -> procedures", "signed_at timestamptz",
            "signature_attachment_id uuid -> attachments", "pdf_attachment_id uuid? -> attachments"]),

    # ------------------------------------------------------------------ ops
    T(name="lab_vendors", domain="ops", rls="clinic",
      purpose="Outside labs: dental labs for crowns, pathology, radiology.",
      cols=["name text", "phone_e164 text?", "kind lab_kind | dental_lab, pathology, radiology"]),
    T(name="lab_orders", domain="ops", rls="clinic",
      purpose="Work sent to a lab, its due date and status.",
      cols=["number text", "vendor_id uuid -> lab_vendors", "patient_id uuid -> patients",
            "practitioner_id uuid -> practitioners", "procedure_id uuid? -> procedures",
            "work_type text | crown, bridge, denture, blood test", "details jsonb | shade, tooth",
            "sent_at timestamptz?", "due_at timestamptz?", "received_at timestamptz?",
            "status lab_status | draft, sent, received, fitted, cancelled", "cost_paise bigint"]),
    T(name="lab_payments", domain="ops", rls="clinic",
      purpose="Money paid to labs.",
      cols=["vendor_id uuid -> lab_vendors", "lab_order_id uuid? -> lab_orders", "amount_paise bigint",
            "paid_at timestamptz", "method payment_method", "reference text?"]),
    T(name="suppliers", domain="ops", rls="clinic",
      purpose="Where materials are bought.",
      cols=["name text", "phone_e164 text?", "gstin text?"]),
    T(name="inventory_items", domain="ops", rls="clinic",
      purpose="Materials and medicines the clinic stocks.",
      cols=["name text", "sku text?", "unit stock_unit | piece, ml, g, box, pack", "category text?",
            "reorder_level numeric", "active bool"]),
    T(name="stock_batches", domain="ops", rls="clinic",
      purpose="Received stock by batch, with expiry and cost.",
      cols=["item_id uuid -> inventory_items", "supplier_id uuid? -> suppliers", "batch_no text?",
            "expiry date?", "quantity numeric | remaining", "unit_cost_paise bigint", "received_at timestamptz"]),
    T(name="stock_movements", domain="ops", rls="clinic",
      purpose="Every change in stock: purchase, use, adjustment, expiry. Stock history comes from here.",
      cols=["item_id uuid -> inventory_items", "batch_id uuid? -> stock_batches",
            "kind stock_move | purchase, consume, adjust, expire, return",
            "quantity numeric | signed", "procedure_id uuid? -> procedures", "reason text?",
            "at timestamptz"]),
    T(name="procedure_materials", domain="ops", rls="clinic",
      purpose="Materials a treatment uses, so stock deducts itself.",
      cols=["price_item_id uuid -> price_items", "item_id uuid -> inventory_items", "quantity numeric"]),
    T(name="equipment", domain="ops", rls="clinic",
      purpose="Chairs, autoclaves, X-ray units and their service schedule.",
      cols=["branch_id uuid -> branches", "name text", "serial_no text?", "purchased_at date?",
            "warranty_until date?", "service_interval_days int?"]),
    T(name="maintenance_logs", domain="ops", rls="clinic",
      purpose="Services and repairs done on equipment, and when the next is due.",
      cols=["equipment_id uuid -> equipment", "kind maintenance_kind | service, repair, amc",
            "done_at date", "cost_paise bigint", "vendor text?", "next_due_at date?", "notes text?"]),
    T(name="salary_structures", domain="ops", rls="clinic",
      purpose="A staff member's monthly salary from a date.",
      cols=["membership_id uuid -> memberships", "monthly_paise bigint", "effective_from date"]),
    T(name="payroll_entries", domain="ops", rls="clinic",
      purpose="Salary paid for a month, with deductions and advances recovered.",
      cols=["membership_id uuid -> memberships", "month date", "gross_paise bigint",
            "deductions_paise bigint", "advance_recovered_paise bigint", "net_paise bigint",
            "paid_at timestamptz?", "method payment_method?"]),
    T(name="staff_advances", domain="ops", rls="clinic",
      purpose="Salary advances given to staff and how much is recovered.",
      cols=["membership_id uuid -> memberships", "amount_paise bigint", "given_at date",
            "recovered_paise bigint"]),
    T(name="consultant_fee_rules", domain="ops", rls="clinic",
      purpose="How a visiting consultant is paid: a percentage or fixed amount per treatment.",
      cols=["practitioner_id uuid -> practitioners", "price_item_id uuid? -> price_items | null means all",
            "kind fee_kind | percent_bps, fixed", "value bigint"]),
    T(name="consultant_payouts", domain="ops", rls="clinic",
      purpose="Payments made to consultants for a period.",
      cols=["practitioner_id uuid -> practitioners", "period_start date", "period_end date",
            "amount_paise bigint", "paid_at timestamptz?", "method payment_method?"]),

    # ------------------------------------------------------------------ billing
    T(name="price_items", domain="billing", rls="clinic", star=True,
      purpose="The clinic's price list. Seeded from the specialty, then edited.",
      cols=["code text?", "name text | Root canal, Scaling, Consultation", "module text?",
            "category text?", "price_paise bigint", "tax_rate_bps int | 0 or 1800",
            "active bool"]),
    T(name="invoices", domain="billing", rls="clinic", star=True,
      purpose="A bill to a patient. Totals are stored; balance is derived.",
      cols=["number text | SC/26-27/000318", "patient_id uuid -> patients",
            "encounter_id uuid? -> encounters", "branch_id uuid -> branches",
            "doc_type invoice_doc | tax_invoice, bill_of_supply",
            "status invoice_status | draft, issued, partially_paid, paid, void",
            "issued_at timestamptz?", "subtotal_paise bigint", "discount_paise bigint",
            "tax_paise bigint", "total_paise bigint", "paid_paise bigint",
            "promo_code_id uuid? -> promo_codes", "pdf_asset_id uuid? -> assets"]),
    T(name="invoice_items", domain="billing", rls="clinic", star=True,
      purpose="Lines on a bill, each optionally tied to a procedure and doctor.",
      cols=["invoice_id uuid -> invoices", "price_item_id uuid? -> price_items",
            "procedure_id uuid? -> procedures", "practitioner_id uuid? -> practitioners",
            "description text", "quantity numeric", "unit_price_paise bigint",
            "discount_paise bigint", "tax_rate_bps int", "tax_paise bigint", "total_paise bigint"]),
    T(name="payments", domain="billing", rls="clinic", star=True,
      purpose="Money received from a patient, by any method.",
      cols=["patient_id uuid -> patients", "received_at timestamptz", "amount_paise bigint",
            "method payment_method | cash, upi, card, bank_transfer, cheque, razorpay, insurance",
            "reference text? | UPI ref, cheque no", "received_by uuid -> memberships",
            "razorpay_payment_id text?"]),
    T(name="payment_allocations", domain="billing", rls="clinic", star=True,
      purpose="Which bills a payment pays, so advances and partial payments work.",
      cols=["payment_id uuid -> payments", "invoice_id uuid -> invoices", "amount_paise bigint"]),
    T(name="refunds", domain="billing", rls="clinic",
      purpose="Money returned to a patient.",
      cols=["payment_id uuid -> payments", "amount_paise bigint", "reason text",
            "refunded_at timestamptz", "method payment_method"]),
    T(name="expense_categories", domain="billing", rls="clinic",
      purpose="Rent, electricity, salaries, consumables and so on.",
      cols=["name text"]),
    T(name="expenses", domain="billing", rls="clinic",
      purpose="Money the clinic spends.",
      cols=["branch_id uuid -> branches", "category_id uuid -> expense_categories",
            "amount_paise bigint", "paid_at date", "method payment_method", "vendor text?",
            "notes text?", "receipt_asset_id uuid? -> assets"]),
    T(name="daily_closings", domain="billing", rls="clinic",
      purpose="End-of-day cash count against what the system expects.",
      cols=["branch_id uuid -> branches", "day date", "cash_expected_paise bigint",
            "cash_counted_paise bigint", "closed_by uuid -> memberships", "closed_at timestamptz"]),

    # ------------------------------------------------------------------ notify
    T(name="message_templates", domain="notify", rls="clinic",
      purpose="Message text per channel and language. Clinic rows override platform defaults.",
      cols=["key text | appointment_reminder, birthday, recall_cleaning ...",
            "channel channel | whatsapp, sms, email, push", "language text", "body text",
            "category message_category | transactional, promotional",
            "provider_template_id text? | Meta or DLT template id",
            "approval approval_status | draft, pending, approved, rejected"],
      notes="org_id is null for platform defaults; this table allows that."),
    T(name="notification_rules", domain="notify", rls="clinic",
      purpose="When to message: on an event, before an appointment, on birthdays, on recalls.",
      cols=["trigger rule_trigger | event, before_appointment, birthday, recall",
            "event_key text? | booking.confirmed, invoice.paid ...",
            "offset_minutes int? | e.g. -1440 for a day before", "template_key text",
            "channels channel[] | in order of preference", "conditions jsonb?", "active bool"]),
    T(name="contact_preferences", domain="notify", rls="clinic",
      purpose="Per patient and channel: may we message them, and was promotional consent given?",
      cols=["patient_id uuid -> patients", "channel channel", "transactional_ok bool",
            "promotional_ok bool", "consented_at timestamptz?", "consent_source text?",
            "opted_out_at timestamptz?"],
      notes="Primary key (org_id, patient_id, channel)."),
    T(name="recalls", domain="notify", rls="clinic",
      purpose="Follow-ups that are due: cleaning in six months, BP review, vaccine.",
      cols=["patient_id uuid -> patients", "kind text | cleaning, bp_review, vaccine, anc_visit",
            "due_on date", "status recall_status | due, notified, booked, dismissed",
            "source_procedure_id uuid? -> procedures"]),
    T(name="audiences", domain="notify", rls="clinic",
      purpose="Saved patient filters for campaigns: age, sex, treatment, doctor, fees, history.",
      cols=["name text", "filter jsonb", "estimated_count int?"]),
    T(name="campaigns", domain="notify", rls="clinic",
      purpose="A one-off or scheduled send to an audience: health tips, offers.",
      cols=["name text", "audience_id uuid -> audiences", "template_id uuid -> message_templates",
            "scheduled_at timestamptz?", "status campaign_status | draft, scheduled, sending, sent, cancelled",
            "cost_estimate_paise bigint?"]),
    T(name="promo_codes", domain="notify", rls="clinic",
      purpose="Discount codes a clinic can share.",
      cols=["code text | unique per clinic", "kind discount_kind | percent_bps, fixed", "value bigint",
            "valid_from date", "valid_to date?", "max_uses int?", "used_count int",
            "applies_to jsonb? | price items or categories"]),
    T(name="promo_redemptions", domain="notify", rls="clinic",
      purpose="Each use of a promo code on a bill.",
      cols=["promo_code_id uuid -> promo_codes", "patient_id uuid -> patients",
            "invoice_id uuid -> invoices", "discount_paise bigint", "redeemed_at timestamptz"]),
    T(name="outbox_events", domain="notify", rls="clinic", star=True,
      purpose="Events written in the same transaction as the change, for the worker to act on.",
      cols=["event_key text | appointment.booked, invoice.paid, report.uploaded",
            "payload jsonb | ids only, no patient details", "processed_at timestamptz?"],
      notes="Guarantees a message is never lost or sent for a change that rolled back."),
    T(name="messages", domain="notify", rls="clinic", partitioned=True,
      purpose="Every message scheduled or sent, with its outcome and cost.",
      cols=["patient_id uuid? -> patients", "user_id uuid? -> users", "channel channel",
            "template_id uuid -> message_templates", "rule_id uuid? -> notification_rules",
            "campaign_id uuid? -> campaigns", "scheduled_for timestamptz",
            "status message_status | scheduled, queued, sent, delivered, read, failed, skipped",
            "skip_reason skip_reason? | no_consent, quiet_hours, duplicate, quota",
            "dedupe_key text | unique, e.g. reminder:appt-id:24h", "provider text?",
            "provider_message_id text?", "cost_paise bigint?", "sent_at timestamptz?"]),
    T(name="message_events", domain="notify", rls="clinic", partitioned=True,
      purpose="Delivery receipts from providers: sent, delivered, read, failed.",
      cols=["message_id uuid -> messages", "kind text", "at timestamptz", "details jsonb?"]),
    T(name="notifications", domain="notify", rls="clinic",
      purpose="The in-app notification feed for staff.",
      cols=["user_id uuid -> users", "kind text", "title text", "entity_ref jsonb | type and id to open",
            "read_at timestamptz?"]),

    # ------------------------------------------------------------------ web
    T(name="sites", domain="web", rls="clinic",
      purpose="A clinic's generated website: template family, repository and live version.",
      cols=["family text | template family key", "template_version text",
            "repo_full_name text? | sakalyatechnologies/site-smilecatchers",
            "status site_status | draft, building, live, failed", "config jsonb | from onboarding answers",
            "live_version_id uuid? -> site_versions"]),
    T(name="site_versions", domain="web", rls="clinic",
      purpose="Each publish of a site, so any version can be restored.",
      cols=["site_id uuid -> sites", "config jsonb", "commit_sha text?",
            "build_status build_status | queued, building, succeeded, failed", "built_at timestamptz?",
            "deployed_url text?"]),
    T(name="booking_requests", domain="web", rls="clinic",
      purpose="Booking requests from the website, before they become appointments.",
      cols=["site_id uuid -> sites", "name text", "phone_e164 text", "practitioner_id uuid? -> practitioners",
            "preferred_at timestamptz?", "message text?", "status booking_status | new, contacted, booked, spam",
            "appointment_id uuid? -> appointments"]),
    T(name="site_daily_stats", domain="web", rls="clinic",
      purpose="Website visits and bookings per day, for the clinic and the console.",
      cols=["day date", "visits int", "unique_visitors int", "booking_requests int"],
      notes="Primary key (org_id, day). Imported from Cloudflare Web Analytics."),

    # ------------------------------------------------------------------ trust
    T(name="consents", domain="trust", rls="user",
      purpose="Phase 3: a patient lets one clinic see records from another, for a purpose and time.",
      cols=["patient_link_id uuid -> patient_links", "grantee_org_id uuid -> organizations",
            "scope jsonb | record kinds", "purpose text", "starts_at timestamptz",
            "expires_at timestamptz?", "revoked_at timestamptz?"]),
    T(name="access_log", domain="trust", rls="clinic", star=True, partitioned=True,
      purpose="Who opened which patient record, when. Patients can see this.",
      cols=["actor_user_id uuid -> users", "actor_kind actor_kind | staff, patient, support",
            "patient_id uuid -> patients", "resource access_resource | chart, note, attachment, invoice, export",
            "resource_id uuid?", "action access_action | view, download, print, export",
            "at timestamptz", "request_id text"],
      notes="Append-only: the app role can insert but never update or delete."),
    T(name="audit_events", domain="trust", rls="clinic", star=True, partitioned=True,
      purpose="Every insert, update and delete, written by triggers.",
      cols=["table_name text", "row_id uuid", "action audit_action | insert, update, delete",
            "actor_user_id uuid? -> users", "changed_fields text[]", "old jsonb? | sensitive fields masked",
            "new jsonb? | sensitive fields masked", "at timestamptz", "request_id text?"],
      notes="Append-only. org_id may be null for platform tables."),
    T(name="data_requests", domain="trust", rls="clinic",
      purpose="Patients' DPDP requests: export, correction, erasure.",
      cols=["patient_id uuid -> patients", "kind data_request_kind | export, correction, erasure",
            "status request_status | received, in_progress, done, rejected", "requested_at timestamptz",
            "completed_at timestamptz?", "notes text?"]),

    # ------------------------------------------------------------------ onboarding
    T(name="onboarding_progress", domain="onboarding", rls="clinic",
      purpose="Where a new clinic is in the first-login wizard, and its answers.",
      cols=["steps jsonb | step key to answers", "completed_at timestamptz?"],
      notes="One row per clinic."),
    T(name="imports", domain="onboarding", rls="clinic",
      purpose="A data import from Excel or old software.",
      cols=["kind import_kind | patients, appointments, invoices", "source text | excel, csv, legacy app name",
            "file_attachment_id uuid -> attachments", "mapping jsonb | column mapping",
            "status import_status | uploaded, mapped, running, done, failed", "total_rows int",
            "imported_rows int", "failed_rows int"]),
    T(name="import_rows", domain="onboarding", rls="clinic",
      purpose="Each row of an import with its result, so failures can be fixed and retried.",
      cols=["import_id uuid -> imports", "row_number int", "raw jsonb",
            "status row_status | pending, imported, failed", "error text?", "entity_id uuid?"]),
]

# How tables are used together. Each step: (who or what, tables touched, what happens).
JOURNEYS = [
    ("onboard", "A new clinic signs up", [
        ("Sakalya console", ["organizations", "org_domains", "subscriptions"], "Clinic created on a trial plan with its subdomain."),
        ("Owner", ["invitations", "users", "memberships", "roles"], "Owner accepts the invite and becomes a member with the owner role."),
        ("Wizard", ["onboarding_progress", "org_modules", "org_settings", "price_items", "working_hours", "practitioners"], "Specialty, branding, prices and hours set up from defaults."),
        ("Website", ["sites", "site_versions", "org_domains"], "Site generated from answers, repository created, built and deployed."),
        ("Import", ["imports", "import_rows", "patients", "patient_identifiers"], "Patients brought in from the old software, keeping file numbers."),
    ]),
    ("visit", "A patient visits the dentist", [
        ("Front desk", ["patients", "patient_identifiers", "referral_sources", "number_sequences"], "New patient registered as SC-1042, or found by name, phone or ID."),
        ("Front desk", ["appointments", "appointment_events", "queue_tokens"], "Appointment marked arrived; token shown on the waiting screen."),
        ("Assistant", ["encounters", "observations", "clinical_notes"], "Visit opened; vitals and intake note recorded."),
        ("Doctor", ["voice_notes", "attachments", "specialty_records", "clinical_notes", "access_log"], "Dictates a note, adds an X-ray, updates the tooth chart; every view is logged."),
        ("Doctor", ["procedures", "stock_movements", "lab_orders", "prescriptions", "prescription_items"], "Root canal done on tooth 36: stock deducted, crown sent to the lab, prescription issued."),
        ("Front desk", ["invoices", "invoice_items", "payments", "payment_allocations"], "Bill SC/26-27/000318 issued and paid by UPI."),
        ("System", ["outbox_events", "messages", "recalls", "audit_events"], "Receipt sent on WhatsApp, a follow-up recall created, all changes audited."),
    ]),
    ("remind", "Reminders, birthdays and recalls", [
        ("Rules", ["notification_rules", "message_templates"], "Clinic has reminder, birthday and recall rules switched on."),
        ("Scheduler", ["appointments", "patients", "recalls", "messages"], "Due messages created with a dedupe key, e.g. reminder:appt:24h."),
        ("Worker", ["contact_preferences", "usage_counters", "messages"], "Consent, quiet hours and quota checked; message sent or skipped with a reason."),
        ("Provider", ["message_events", "messages"], "Delivery and read receipts recorded; cost metered per clinic."),
    ]),
    ("finance", "Month-end finance report", [
        ("Money in", ["payments", "refunds", "payment_allocations", "invoices"], "Collections by doctor, treatment, referral source and payment method."),
        ("Money out", ["expenses", "lab_payments", "payroll_entries", "consultant_payouts"], "Spending by category, lab, staff and consultant."),
        ("Report", ["daily_closings"], "A ledger view joins both sides; exported to Excel by the worker."),
    ]),
    ("access", "A request checks access", [
        ("Host", ["org_domains", "organizations"], "smilecatchers.arogyam.app resolves to the clinic."),
        ("Session", ["users", "sessions"], "JWT verified, session still active."),
        ("Membership", ["memberships", "roles", "role_permissions"], "User is an active member whose role allows patients.read."),
        ("Plan and flags", ["subscriptions", "plan_features", "entitlement_overrides", "feature_flags", "flag_rules"], "Feature is in the plan and released to this clinic."),
        ("Database", ["patients"], "Row-level security limits every query to this clinic."),
    ]),
    ("quality", "Test results reach the super admin", [
        ("CI", ["quality_runs", "quality_results"], "Every pull request and merge uploads unit, integration and end-to-end results."),
        ("Canary runner", ["canary_checks", "quality_runs", "quality_results"], "Every 15 minutes each journey runs against the demo clinic; failures carry the request ID."),
        ("Console", ["quality_runs", "quality_results"], "Quality page: status per suite and environment, pass-rate trend, flaky tests, failing request IDs to open with sk."),
    ]),
    ("patient", "Phase 3: a patient sees all their clinics", [
        ("Patient", ["users", "patient_links"], "Patient signs in with their phone and verifies records at each clinic."),
        ("Patient", ["consents"], "Patient lets their new cardiologist see their dental and GP records."),
        ("Cardiologist", ["encounters", "prescriptions", "attachments", "access_log"], "Reads the shared records; the patient sees who looked."),
    ]),
]
